### ISSUE TITLE
Problem loading v0.6.4 lisp api

### ISSUE THREAD

**Issue by jesulo** [turtl/tracker#104]
> Error: Unexpected end of file on #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/t                                urtl/.ccl-init.lisp"/4 UTF-8) #x3020004BC71D>, near position 275
> While executing: CCL::READ-CHAR-INTERNAL, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading init file.
> Type :? for other options.

in ubuntu 16.04
I can' t finish the installation for that, can help me? thanks!

**Comment by orthecreedence** [comment]
Can you post your `/home/turtl/.ccl-init.lisp` file?

**Comment by jesulo** [comment]
I followed the steps in this tutorial:
https://www.linode.com/docs/applications/cloud-storage/how-to-install-a-turtl-server-on-ubuntu/

/home/turtl/.ccl-init.lisp file : 


;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init))
(cwd "/home/turtl/api")
(load "/home/turtl/api/launch")

**Comment by orthecreedence** [comment]
Try this:

```lisp
;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init))) ;; <-- needed an extra paren
(cwd "/home/turtl/api")
(load "/home/turtl/api/launch")
```
