### ISSUE TITLE
Viewing FIles on Mobile is Currently Broken.

### ISSUE THREAD

**Issue by jordansinn1994** [turtl/tracker#105]
Unable to open or download file attachments created on the PC application from the Android app. When tapping on the link the message ,  "Viewing files on mobile is currently broken. We're working on a fix. Sorry for the trouble!" is displayed. I remember this issue from trying to use turtl years ago, has any progress been made on this?

**Comment by orthecreedence** [comment]
Yes, this should be fixed in the upcoming [v0.7.0 release](https://github.com/turtl/tracker/milestone/1). This should be released soon!
