### ISSUE TITLE
Images in shared spaces not syncing/showing

### ISSUE THREAD

**Issue by jacobc-eth** [turtl/tracker#106]
I'm using the Linux desktop client to collaborate together when another user of Turtl. When I add an image, the other user can see an image was added, but they cannot view the image itself. Instead they simply see a black card with the photo icon in the center. If the other turtle user adds an image to the shared board, I'm unable to see the image as well (but they can see the image they added).

**Comment by orthecreedence** [comment]
The syncing system has been completely rebuilt for the upcoming v0.7.0 release, so I'm guessing this is fixed now. That said, I'll test this specific case before closing this issue.

**Comment by orthecreedence** [comment]
Note that this is now blocked by #110

**Comment by orthecreedence** [comment]
Confirmed fixed.
