### ISSUE TITLE
Undifined text all over on the login screen

### ISSUE THREAD

**Issue by janos-szenfner** [turtl/tracker#108]
![2018-07-23 16_13_52-turtl](https://user-images.githubusercontent.com/27774520/43082164-af82fd32-8e93-11e8-9144-9cf2fc4c21c0.png)

This is viewable when open the app on Windows 10 x64 bit -  Turtl 7.0-RC1

**Comment by orthecreedence** [comment]
@janos-szenfner I think this is related to the blank android screen bug you reported earlier, which I have an idea on how to fix. Both these issues seem to be related to a recent bug in the locale system. Once that's fixed, I'll send out another round of releases to check out.

Thanks for reporting!

**Comment by orthecreedence** [comment]
Confirmed fixed in https://github.com/turtl/js/commit/57d8a45783fea2674a9711ecb3ce4067a38e2752
