### ISSUE TITLE
Filter HTML when barfing error messages

### ISSUE THREAD

**Issue by janos-szenfner** [turtl/tracker#115]
![2018-07-25 08_18_18-turtl](https://user-images.githubusercontent.com/27774520/43182908-85c47c40-8fe3-11e8-98c9-8a4c4b67cbb7.png)

The screen jumps into smaller screen on windows 10 x64 - Turtl7.0-RC2

The error should looks like within the entire window.

**Comment by orthecreedence** [comment]
This is caused by pointing the client at a server that returns an HTML error, and the HTML is being displayed on the page and messing with the layout. The solution would be to filter HTML when printing error messages like this.
