### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by janos-szenfner** [turtl/tracker#116]
When I try to login it gives back error.

![2018-07-25 08_18_18-turtl](https://user-images.githubusercontent.com/27774520/43183238-bc5c75d6-8fe4-11e8-933d-4daacbb713b0.png)

System: Windows 10 x64
Turtl: 7.0 RC2

**Comment by orthecreedence** [comment]
I think your client has saved the url of the old server. Can you open "Advanced settings" and change "Turtl server" to `https://apiv3.turtlapp.com`? That should fix it.

**Comment by janos-szenfner** [comment]
You can close this ticket. The server address was not correct.

**Comment by orthecreedence** [comment]
Thanks for verifying!
