### ISSUE TITLE
Use as general filesystem

### ISSUE THREAD

**Issue by leonhardvohla** [turtl/tracker#118]
I don’t know if this project aims in that direction at all, but I would like to use Turtl to store all my files, photos and notes and thus be able to tag and search through them all.

It would be easier if you could:
- mount your storage in your filesystem/webDav access (only for files and images, don’t think it would work for notes)
- easily open files (like .docx, .html, etc.) in a program of choice and sync it back to the server on saving it
- batch upload images/files

**Comment by orthecreedence** [comment]
Turtl does store your files on the filesystem, in the new version. It stores them into the user directory alongside the main db (which holds the profile locally). It would be possible to change this location by changing the desktop configuration file.

However, these files are encrypted and there's no way you'd be able to open with any external program without downloading them through Turtl first. It sounds like you want something like https://www.tagspaces.org/, which uses the current filesystem and lets you tag and search through them (without encryption).
