### ISSUE TITLE
App randomly becomes unresponsive

### ISSUE THREAD

**Issue by shaneparsons** [turtl/tracker#119]
**What happened:**
The app randomly becomes unresponsive. It's happened about 5 times now, within an hour.

**What was I doing:**
I was just adding "password" entries.

**How to resolve the issue:**
The only thing that seems to work for me is quitting / re-launching the app.

**Other details:**
- turtl-osx-0.6.4
- macOS: 10.13.5

**Comment by orthecreedence** [comment]
Thanks for reporting!

I believe this has been fixed and the release (v0.7.0) will be out soon. So I am going to close this for now.

Please keep an eye out for the new release!
