### ISSUE TITLE
Im- and export all notes

### ISSUE THREAD

**Issue by opensource21** [turtl/tracker#120]
It should be possible to im- and export all notes. There is no cryptographic necessary, because it should be a simple backup mechanism.  All notes should be in Markdown-Format. It could be a JSON-Format or a file-structure.
There are 4 main reason to implement it:
 
1. Backup-Mechanism are always a good idea for the case that the turtl server  isn't reachable.
2. Based on European law a service-provider must provide the data to make it possible to change the provider.
3. It makes it easier to test a new version.
4. If client synchronization becomes broken, you can save the data in an easy way.

 It seems to be an easy job, put all notes in a list and write down as JSON, but I'm not very common with JS and doesn't find a starting point.

**Comment by orthecreedence** [comment]
Although there's no issue tracking this (unless you count the old trello: https://trello.com/c/a5rl9dKY) this is done and set to release in v0.7.0!
