### ISSUE TITLE
Text editor: mobile keyboard covers text box even if focused

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#13]
> When using the app on a phone, the keyboard covers a half of the screen. Suppose there is already some text and clicking on that text brings up the onscreen keyboard. At that time, the few lines of visible text do not scroll to the bottom and we have to scroll annually in yhr small area between the top part of the app and the keyboard to reach the writable portion of the text.

need to confirm the auto-resize fixed this issue.

**Comment by opensource21** [comment]
For me this seems an old bug, perhaps it's better to finish the switch to RUST and fix then old issues. Otherwise the new architecture will never finished.

**Comment by orthecreedence** [comment]
Oh, completely agree, @opensource21 . The old version is dead to me. This issue is really just to check that the problem doesn't still exist. Much of the UI is the same as the old version, so it's possible it didn't get fixed.

**Comment by orthecreedence** [comment]
Just confirmed. Fixed.
