### ISSUE TITLE
Add version number to releases/downloads

### ISSUE THREAD

**Issue by dave-theunsub** [turtl/tracker#130]
Hi,

Recommend adding the version to the releases or any downloads. Currently the downloads look like "turtl-linux64.tar.bz2" - but "turtl-v0.7.0-rc4-linux64.tar.bz2" or something would be easier for maintainers and users.

Thanks!

**Comment by orthecreedence** [comment]
Yes, I can do this. I think originally I wanted to, but did not because it would have made generating the SHA256 sums slightly more involved with the automated build process I have. Seems it might be worth putting int he time to include the version though.

**Comment by orthecreedence** [comment]
Note to self: need to remember to update the new www site to embed the version in the download links.

**Comment by orthecreedence** [comment]
This is done, will take effect on the next RC release.
