### ISSUE TITLE
OpenSSL verification errors (need to bundle CA list with desktop build)

### ISSUE THREAD

**Issue by naraesk** [turtl/tracker#131]
I've installed RC4 on Arch Linux successfully. I tried creating a new account account and run into several issues. I will document them all here. Please note, I used it in German. I always write my own back translation, hope you can work with that. Is there an easy way change language without changing it globally?

1) After clicking on "Ein Konto erstellen" ("Creating an account") I see the following screen:
![screenshot_20180808_113927](https://user-images.githubusercontent.com/7393797/43829642-b89e7e28-9aff-11e8-9f80-b08ec817ca4f.png)

Besides the strange alignment, there seems to be a text missing. The heading says "A hint about the functionality of turtl" but nothing follows.

2) Next screen, after clicking on "Ich werde meine Zugangsdaten nicht vergessen" ("I will not forget my login credentials")
![screenshot_20180808_114304](https://user-images.githubusercontent.com/7393797/43829832-38daf1f2-9b00-11e8-9ab8-1c6141101945.png)

- In the first line the explenation is missing. Am I supposed to enter a username or an mail address?
- By clicking on "Teilnehmen" ("Participate") I recieve an error: "Please enter a username 3 characters or longer." This is fine since I haven't entered a username. I entered a username (naraesk) in the first line. Now, by clicking on "Teilnehmen" nothing happens. No error message, not going to the next screen. Accidentally I saw the tooltip for the first line: an @ was missing, since I have to enter an mail address. This should be shown as error message! 
- After entering a mail address I clicked on "Teilnehmen" again. I recieved the following error: "An error in the OpenSSL library: certificate verify failed". openssl is installed, do I need a specific version?

**Comment by matthewn** [comment]
I can confirm the SSL error. I have successfully installed 0.7 RC4 on Ubuntu 18.04, but any attempt to log in is met with "Login failed: An error in the OpenSSL library: certificate verify failed".

**Comment by orthecreedence** [comment]
The issue with the missing text should be pretty easy (I think it's just a setting in the localization library to ignore blank entries), so I'll focus this issue on the openssl failure. Looks like I may have to bundle the CA list with the desktop app like I do with android.
