### ISSUE TITLE
Can't select a board that is in a different space.

### ISSUE THREAD

**Issue by peakgeek** [turtl/tracker#133]
Imported all of my notes from the previous version, loved the idea of the different "spaces" and started moving my boards accordingly. There are still a number of notes that are in the "Imported" space that weren't assigned to boards. Now that there are no boards left in the "imported" space I can't move those notes anywhere. When editing one of the notes, the "select board" drop-down is empty. 

It's not a major issue, but a little clunky. I'll have to now create new boards, assign the notes, move the boards to different spaces, and then move the notes from the newly created boards to ones that are more appropriate. It would be much easier if you could select a space and a board right from the note edit screen.

I love turtl and I'm digging the updated design. Keep up the good work.

**Comment by orthecreedence** [comment]
Thanks for the feedback! This is slated to be released with 0.7.1 (I wanted to focus on bigger issues for 0.7.0): #83
