### ISSUE TITLE
Android app fails to load properly

### ISSUE THREAD

**Issue by Shamp0o** [turtl/tracker#136]
I cannot get the Android app to load properly on either of my phones (mako and whyred). When launching the app I get the white screen with the turtl icon at the top left but the login query is missing.

**Comment by orthecreedence** [comment]
Which version of Turtl? Is this the 0.7.0 from here? https://github.com/turtl/android/releases

**Comment by Shamp0o** [comment]
yes, exactly. The -rc4 one in particular.
Version 0.6.4 from the Play Store works but is extremely laggy.

**Comment by orthecreedence** [comment]
Is there any chance you have you used remote webview debugging via chrome before? If so, it would be really helpful if you could send me a screenshot of the console error you're getting when loading the app.

Although, after all the whitescreen errors people are getting when trying to load the app, I think I might just need to build in an error page that displays the problem.

**Comment by Shamp0o** [comment]
I'm sorry, I've never done that before.

**Comment by orthecreedence** [comment]
No problem, that might actually be a good thing since I need to build an error screen for when that happens.

**Comment by jacobc-eth** [comment]
I am also having the exact same issue with both rc4 and 0.6.4.

I don't recall ever using the remote webview. I use the Linux desktop app and the Android app only.

**Comment by orthecreedence** [comment]
Hi, everyone. I just released RC5 (https://github.com/turtl/android/releases/tag/v0.7.0-rc5). This includes a change that should (hopefully) show what the error is when loading without need you to do any kind of debugging.

Please give it a shot and let me know if it spits out anything interesting. This won't fix the loading issue, but it may point in the right direction. Also, if anyone having issues loading could let me know what kind of device they are using, that might help narrow the problem down as well.

Thanks!

**Comment by Shamp0o** [comment]
For some reason RC5 is working just fine on both of my devices. Loading issues are gone. Thanks for doing this, by the way.

**Comment by orthecreedence** [comment]
@Shamp0o thanks for reporting! That's weird it fixed itself, but I'm glad it works now =].
