### ISSUE TITLE
Desktop: OSx copy/paste not working

### ISSUE THREAD

**Issue by microcreators** [turtl/tracker#139]
cmd+c / cmd+v shortcuts don't work and aren't assigned to the actions? a bit painful while migrating from Keep or when creating check lists. this is 0.7 rc5

**Comment by orthecreedence** [comment]
Thanks, I'll check this out.

**Comment by orthecreedence** [comment]
@microcreators can you give rc9 a shot? I think this might be fixed. https://github.com/turtl/desktop/releases/

Thanks!

**Comment by orthecreedence** [comment]
Probably works! Closing.
