### ISSUE TITLE
Android: tagging inconsistent

### ISSUE THREAD

**Issue by microcreators** [turtl/tracker#143]
On mac, whenever I press `comma` or `enter` the tag is recorded. Cool. 
On android it works differently and there are 2 problems there:

- `comma` doesn't attach a tag
- even if you type several tags properly separated and press `done` button, they aren't saved. Why? Because you need to press `enter` first. It's just not obvious.

IMO either fix the `comma` thing or parse and save properly when leaving a note. I'd say option 1.

**Comment by orthecreedence** [comment]
Good notes! I will see about fixing this on Android.
