### ISSUE TITLE
Overall UX and so much clicking

### ISSUE THREAD

**Issue by microcreators** [turtl/tracker#144]
So I've been using Turtle for a few days now and I like it. I'm considering moving out of other solutions, but the more I use Turtl, the more I'm convinced the UI/UX can be improved. There's so much clicking around for everything... My impression below. Don't look at it as me being pain in the azz, but rather an attempt to make things a bit faster and more intuitive.

_ranting mode on_

**Basic inconsistencies**. Sometimes there's `save` button, sometimes `done`. They do same thing, so why different names?
**But why that button anyway**? I'd be perfectly fine when the content of a note is autosaved after pressing the arrow at the top of it, or simply outside of a note. That button is a duplication.
**Leaving? Sure?** I am sure I want to leave a note. Just stop asking and save my changes damn it. I could always delete a note or edit it later. It's connected with the point above (the arrow works differently than the button, we don't need both).
**Big one. The path to editing**. This is major pain for me. If I need to edit a note I need to: 
- find a right board or search
- click on the note
- click on edit
I'd love to edit once a note is open. I'd love to tag notes without being forced to edit. I'd be OK to go into edit mode when a note is dbl-tapped or clicked.

**Connected. Yes, I know**. I mentioned that on G+, but everytime I unlock a phone, Turtl informs me it got online. Multiple times. I really don't care as long as it does syncing in the back. And yes, I'm staying online all the time.

_ranting mode off_
;)

**Comment by orthecreedence** [comment]
Thanks, all very helpful.

Regarding Save vs Done, can you tell me the places you saw "Done?" I think I found one in the note tag editor, but if you know of any more let me know. I will change these to "Save." 

As far as auto-saving goes, This is probably something that will happen soon enough. We've gotten enough requests for it (and it seems to be the norm with other note apps) that I think it makes sense.

I'd like to have something like long-press to edit a note. I'm still not sure if I want to get rid of the note view altogether, but agree that some kind of shortcut to make editing quicker would be good. I'll think about this more.

For the connection notification, please see #150. I might split your list further into separate issues as I work on them.

**Comment by orthecreedence** [comment]
I'm going to close this now, since all the separate issues have been created.
