### ISSUE TITLE
Migration choking on utf8 characters from v0.6

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#147]
Seems we get:

```
2018-08-23T13:12:35 - [WARN][migrate] migrate::decrypt_profile() -- cannot decrypt note 01652b3e51153cdec14a8b13c19480b67cf0388673be3dd53bcdbb44235ed3d83c49ba1ef6d200c9: error: invalid utf-8 sequence of 1 bytes from index 3978
```

when there are utf8 characters (or even `&`) in notes. Needs investigation before release. A user who reached out has a fairly repeatable test case, so be sure to follow up w/ them over email if reproduced/fixed.

**Comment by orthecreedence** [comment]
Not able to reproduce this at all. Tried with a number of different languages, gibberish, binary data, different note lengths, etc. I've confirmed that both the offending notes and my notes are encoded with the stupid "utf8" byte.

I'm going to use from_utf8_lossy when decoding the notes from the migration and hope for the best.

**Comment by orthecreedence** [comment]
The person who reported this gave specific characters that were breaking:

```
çéêüëöíïīîìßēñáæå
```

I tried adding these to various notes in various combinations to a ffresh 0.6 account and importing it. No errors at all; everything utf8-decoded just fine. However, they are able to reproduce consistently. The commit above allows migration, but replaces the failed characters with the utf8 `<?>` (unknown char).

User reports the problem is somewhat intermittent, so maybe I just need to try importing several more times on the same profile.

**Comment by orthecreedence** [comment]
Just migrated my test account (v0.6 -> v0.7) about 20 times. No errors. And it has plenty of UTF8 characters.

**Comment by orthecreedence** [comment]
@lambd0x Good news! Just migrated your test account:

```
2018-09-11T07:20:24 - [WARN][migrate] migrate::decrypt_val() -- UTF8 decoding error (attempting lossy decoding): invalid utf-8 sequence of 1 bytes from index 97
2018-09-11T07:20:24 - [INFO][turtl_core::messaging] messaging::ui_event() -- migration-event
2018-09-11T07:20:24 - [WARN][migrate] migrate::decrypt_val() -- UTF8 decoding error (attempting lossy decoding): invalid utf-8 sequence of 1 bytes from index 93
```

So it breaks for me migrating your account. Here's what I can tell:

- Migration breaks for you when importing *your* v0.6 account
- Migration breaks for me when importing *your* v0.6 account
- Migration works for me when importing *my* v0.6 account

My guess is that the v0.6 version is encoding UTF8 poorly (maybe based on the device's locale?). The bad news is if the v0.6 version is creating bad encoding then v0.7 is working with bad data, and might need more robust character decoding if it's going to work.

I'll start looking into character encoding. The good news is I at least have a test case now. Thanks for helping!

**Comment by orthecreedence** [comment]
I think this is fixed. I assumed all our strings were UTF8. They are not. In fact, Javascript encodes strings as UTF16. However, some of the data was apparently being stored as Latin1 encoding. I'm not going to lie and say I understand the details of which encoding is used when. However, the migration process now tries UTF8, Latin1, UTF16 (in that order), only failing if all three encodings fail, and then using utf8 lossy decoding as a fallback (the funny question-mark diamonds).

The test profile created by @lambd0x worked after this change, and the migration crate tests the string that was failing to make sure it stays working.

**Comment by l4mbd0x** [comment]
Am glad for being of help :).

**Comment by orthecreedence** [comment]
Thank you!
