### ISSUE TITLE
Inline JavaScript is not enabled

### ISSUE THREAD

**Issue by monnypython** [turtl/tracker#149]
I had some trouble by build the Desktop-App on Arch because i'm not a "Linux-build-pro".
The build process of core and desktop are successful (build problems with openssl i had solved with this information: [https://blog.tribly.de/2017/06/28/Rust-Arch-OpenSSL/](https://blog.tribly.de/2017/06/28/Rust-Arch-OpenSSL/).
After run `make run` in desktop folder i get this java error.
How can i fix this?

---
make[1]: Verzeichnis „/home/markus/turtl/js“ wird betreten Less: css/modules/item-actions.less -> build/css/modules/item-actions.css
SyntaxError: Inline JavaScript is not enabled. Is it set in your options? in /home/markus/turtl/js/css/modules/item-actions.less on line 10, column 120:
9 	}
10 	> .menu {display: none; position: absolute; z-index: 51; top: 0; right: 0; width: 170px; height: 0; overflow: hidden; .transition(height .15s); .card();}
11 	> .menu {

make[1]: *** [Makefile:79: build/css/modules/item-actions.css] Fehler 1
make[1]: Verzeichnis „/home/markus/turtl/js“ wird verlassen
make: *** [Makefile:92: build/make-js] Fehler 2

<del>I am not sure how to start the app after compiling is finish.

<del>`node main.js`

<del>gives this error:

<del>node main.js 
<del>/home/markus/turtl/desktop/build/config.js:6
<del>		require('electron').app.getVersion() :	                       
<del>TypeError: Cannot read property 'getVersion' of undefined
<del>    at /home/markus/turtl/desktop/build/config.js:6:26
<del>    at Object.<anonymous> (/home/markus/turtl/desktop/build/config.js:26:3)
<del>    at Module._compile (module.js:652:30)
<del>    at Object.Module._extensions..js (module.js:663:10)
<del>    at Module.load (module.js:565:32)
<del>    at tryModuleLoad (module.js:505:12)
<del>    at Function.Module._load (module.js:497:3)
<del>    at Module.require (module.js:596:17)
<del>    at require (internal/module.js:11:18)
<del>    at Object.<anonymous> (/home/markus/turtl/desktop/main.js:9:16)
<del>

---

Edit:
After several make run the process ends and Turtl starts and looks like this
[login screen](https://markus-adler.de/nextcloud/s/PKxXGRkMKZQFjae)
The problem is probably the disabled "inline javascript" in less during the make process.
Does anyone know how and where to activate it?

**Comment by orthecreedence** [comment]
Looks like it's trying to interpret `.card()` in the CSS as javascript, which means `lessc` didn't run. The most likely cause would be that you may not have run `npm install` in the `js/` folder. If you did, try running it again anyway, then doing `make run` in `desktop/`. Be sure to follow all the steps here: https://github.com/turtl/desktop/#setup

**Comment by monnypython** [comment]
I did all the steps exactly following the instructions, but I found a solution. The problem is the disabled inline javascript starting at less 3.x. I did the following before the make run: 
`npm uninstall less` and 
`npm install less@2.7.0.` 
After that, the make-run process ran smoothly. Everything is going beautifully now.

Love turtl now ;)

**Comment by orthecreedence** [comment]
Glad that worked!
