### ISSUE TITLE
Backspace not working properly in editor on Android

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#154]
From a `v0.6.4` user:

> When I select a word or character and press backspace on the Android app to delete text it deletes the wrong characters. For example, I wanted to delete a bullet point markdown (i.e: *) of a new sentence and the app started deleting text from the end of the previous sentence...

I haven't verified this yet on v0.7.0.

**Comment by l4mbd0x** [comment]
This is very true for the v0.6.4 release.
However I've been using the latest (rc-13) release over Android and I've noticed this problem no longer happens :).

**Comment by orthecreedence** [comment]
Confirmed, now working on android. Closing. Thanks for giving it a try =]

**Comment by warbe-maker** [comment]
I am using GitHub.com on my Android Tablet and Android Smartphone and the backspace key is not deleting anything at the left.
