### ISSUE TITLE
Settings should have a back button to your last open space

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#160]
When a user goes from any specific space to access its settings the process required in order to go back to this very space is:
1. Click over your settings
2. Click over All notes.

Instead of it, it would be better and also intuitive to have a back/return button on the Settings menu such as the attached for illustrative purposes to return to the current space.
![aaa](https://user-images.githubusercontent.com/14299648/45635144-a01f9180-ba7a-11e8-88c8-d64dfb6d6ce2.png)

**Comment by orthecreedence** [comment]
This is a GREAT idea.

You're right, it's annoying that it doesn't remember where you came from and have a back button. I'll add this into the next release.

**Comment by orthecreedence** [comment]
This is fixed and will go out in the next release!
