### ISSUE TITLE
Convert line breaks to <br> in note editor

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#162]
This is a pretty highly requested feature, and just makes sense TBH. Do we really expect people to do double-space? Let's meet in the middle here.

**Comment by taw00** [comment]
Can we make this configurable? I.e., in settings (and therefore the preferences file) you could add a "Render all line breaks as hard breaks" or some such and have the "break: true" bit flipped in main.js (md_opts).

Personally, this line break issues makes me pull my hair out. Most editors honor traditional markdown line breaking. Except, for some reason, a few of these desktop note editors. It's a bit maddening. And **It degrades the markdown's portability**.

If I have time this spring,  I may try to hack together something and submit it as a pull request. But... gah!

In the meantime, I wrote a shell script that uses `sed` to flip that "breaks: true" bit to "breaks: false".

**Comment by taw00** [comment]
I opened a separate RFE on this topic: https://github.com/turtl/tracker/issues/303
