### ISSUE TITLE
www revamp/redesign

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#165]
Add a feature list and some more screenshots. Maybe use some turtle imagery. Really want to keep away from it looking like an open-source project website like many others (Omni/Joplin). Needs to retain its "this is a product" look/feel.

Some good examples:

- https://products.office.com/en-us/onenote/digital-note-taking-app
- https://evernote.com/
- https://simplenote.com/ (a bit bland for Turtl, but still good elements)

**Comment by trymeouteh** [comment]
I think turtl looks good with the green look but a little touch up here and there would make it look sleek. I suggestion is to use less black and more white or a light grey.

**Comment by orthecreedence** [comment]
This is done, going to push soon. Closing.
