### ISSUE TITLE
Turtl android release candidates on same commit

### ISSUE THREAD

**Issue by eternaltyro** [turtl/tracker#166]
All turtle releases from RC6 - RC12 are off the same commit: https://github.com/turtl/android/commit/2b783491b730d5f07026ee71c26ca917ba3b2bf7

https://github.com/turtl/android/releases

**Comment by orthecreedence** [comment]
This is fine. The Android app bundles resources from the [core](https://github.com/turtl/core-rs) and [js](https://github.com/turtl/js) projects, so if those change, we will release a new RC along with Desktop. Although the commit in Android doesn't change, it's bundled with new assets/libraries.
