### ISSUE TITLE
Changing note tags requires restart for tags to show in search

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#167]
@orthecreedence  remember those chars which used to broke the migration from 0.6.x release to the 0.7.x release? Well, they attack again :P.

This is related to the tagging system Turtl uses and has some case scenarios. 

a) On the 0.6.x release when any special char would be used along as part of a tag identifier it would glitch two areas:
1. It would first add junk chars to the tag identifier after saving it for that specific note and would increment junk post each edit over that very tag identifier for as long as the special char is kept.
2. It would not display the tag identifier when one left the closed note and went to search using the very tag identifier. (It would require the user to restart the app for the tag identifier to appear on the list for search). This behavior happens regardless of being a tag with special chars or not.
3. Additionally, if the tag identifier had special chars and the user interacted with this tag identifier then the search would just vanish with all notes and boards, the tagged note won't appear.

b) On the v0.7.0-rc9 release the previous situation is as follows.
1. No longer injects junk over the tag identifier when there are special chars.
2. Persists.
3. Persists.

My latest case scenario which arose this error was creating a note for my friends of D&D where the & symbol caused the problem, but this happens with all the special chars presented on #147 and likely with ¹, ², ³, $, %, * symbols too.

**Comment by orthecreedence** [comment]
I am seeing this too! Fix on the way...

**Comment by orthecreedence** [comment]
This is fixed! The tags now update as notes are added/edited/deleted. This will go out in rc13!
