### ISSUE TITLE
Turtl's markdown parser doesn't allow for nested itemize-like and enumerate-like lists.

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#174]
Over the current implementation (rc13) of Turtl it doesn't allow one to nest items (neither the itemize-like items nor the enumerate-like lists).

So Turtl's support should allow one to
- a
  - a
  - a
    - a 
      - a
         - a

1. a
   2. a
   3. a
      4. a 
        5. a
           6. a
Even Github's support doesn't allow for more than two enumerate-like lists. But Turtl's having it would be awesome :).

It doesn't need to change the list identifier symbols in accordance to the layer of the list, rather just adding the nested support would allow one with much more expressionism through the list usage.

**Comment by orthecreedence** [comment]
Closing this in favor of #173 (mainly because we don't parse our own markdown, so we're kind of at the mercy of markdown-it).
