### ISSUE TITLE
File upload failure

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#176]
A user reported a file failing to upload, and then reported a 5gb data usage ont heir mobile device. Obviously, this is a serious issue. I'm wondering if it's related to #175 but very well could be different.

Sync info:
```
'file:outgoing (add - 12 days ago)  Ready to Sync'
```
Debug log (shown every 1s):
```
[ERROR][turtl_core::sync] sync::runner() -- files:outgoing: main loop: {"err":{"message":"file not found", "type";"not_found"},"file":"scr/models/file.rs","line":192,"wrapped":"true}
```

Will post any more relevant info as I get it.

**Comment by l4mbd0x** [comment]
What is the maximum file upload size @orthecreedence ?

**Comment by orthecreedence** [comment]
@lambd0x I don't believe there is a maximum. This was happening on the user's own server instance, so it would be up to their router/server setup. They tried uploading larger files after this and didn't have an issue, so I think something else happened here.

**Comment by l4mbd0x** [comment]
OK.

**Comment by orthecreedence** [comment]
More info from our mailing list user:

Further I found appr 2500 server-nginx.log entries ending around the time  I 'Cleared Local Data'
``` 
PUT /notes/0165c7eb304aed2906b356a0e22b63888a69bc649c00c9ed063ab62d5f46007ba42457cf63730011/attachment HTTP/1.1" 404 47 "-" "-"
```

Also:
```
debug: db: query:  SELECT * FROM notes WHERE id = $1 LIMIT 1 0=0165c7eb304aed2906b356a0e22b63888a69bc649c00c9ed063ab62d5f46007ba42457cf63730011
  error: tres.err -- (uid 53): that note doesn't exist
```

I think I know what happened:
- There were two clients at play
- Client A creates note with attached file
- Client A syncs note, waits for success response before trying to sync file
- User on Client B sees that note hasn't synced yet (it's just a black box) so deletes the note
- Client B syncs the `note.delete` *as the file is uploading*
- Client A finishes the upload, but the server says "lol wut that not isn't here"
- Client A tries the upload again, fails
- Client A tries the upload again, fails...

So in this scenario, Client A needs to read the 404 code being (correctly) sent from the server and instead of trying to upload incessantly, delete the local file and outgoing sync.

This should be easily testable with two clients of any type and a sufficiently large enough file (that takes more than a few seconds to sync). In fact this is ripe for an integration test (upload note with file, logout, delete note, log back in, continue upload).

**Comment by l4mbd0x** [comment]
Agreed.
One observation, shouldn't Turtl actually finish the file upload before displaying the existence of the file to user B? This way user B won't be able to act upon the uploading file and this would also avoid similar issues.

**Comment by orthecreedence** [comment]
This is a great idea, it should either mark the file as pending or not show it at all. I'll see if I can throw that in while fixing this.

**Comment by orthecreedence** [comment]
I split this idea off into a separate issue: #178
