### ISSUE TITLE
Space title takes a resync (logout and then login) to update */*-like titles 

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#181]
It happens with the latest release candidate (rc-13).
All space titles will update without a problem once an user edit them (right after that the updated title is displayed over the spaces list). However, if a title is alike to the regular expression \* / * it will cause the title not right after being displayed. Requiring the user to logout and then login to have this space title updated.

**Comment by orthecreedence** [comment]
Thanks, I'll check this out.

**Comment by orthecreedence** [comment]
Seems that spaces only ever change once no matter what the title is. So you edit it once and it updates, if you edit it again it doesn't update.

**Comment by orthecreedence** [comment]
Fixed in https://github.com/turtl/js/commit/c01f365dfa355261a379c6c85b7e4b6963b6ea9b

**Comment by l4mbd0x** [comment]
Nice job, man!
