### ISSUE TITLE
Turtl crashes on migrate

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#188]
This is a high-priority issue affecting many users. I was finally able to reproduce this. I'm not able to dig into the specifics of the problem at the moment, but suspect OOM.

**Comment by l4mbd0x** [comment]
This problem is anyhow related to #187? or the others about issues with the migration process @orthecreedence?

**Comment by betsythefc** [comment]
I updated to 0.7.0 and was prompted to migrate. I am receiving this error:
![screen shot 2018-10-08 at 3 46 04 pm](https://user-images.githubusercontent.com/15450365/46637530-6b4ea980-cb11-11e8-9185-ae841b83aa86.png)

I am on macOS 10.13.6, updated from v0.6.4

**Comment by orthecreedence** [comment]
@lambd0x Issue #187 was a server issue caused by something I did last night. I'm debugging this issue and seeing it's a low-level problem having to do with one of crypto libraries we use when running the migration.

@betsythefc can you try again? I think that's another server-specific error that has been fixed (or, I hope it has).

**Comment by orthecreedence** [comment]
As far as I can tell, this has been fixed. I had to implement our own constant-time vector comparison function and work around rust-crypto assembly one, but this shouldn't be a problem since a) we don't really need to worry about timing attacks here and b) the workaround should be constant-time enough anyway.

**Comment by betsythefc** [comment]
FYI this fixed it for me, Thanks!
