### ISSUE TITLE
Classic (v0.6) logins not always working on v0.7 client

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#190]
I'm not able to verify this yet. Might have something to do with a space in the password? Need to run some tests here.

**Comment by orthecreedence** [comment]
Nope, all combos I do (even with a known non-working username thanks to one of our users who reported) seem to pass the auth test. This is with the v0.7.0 release build, not the new one with encoding fixes.

Not sure what to make of this. Here's what we know.

- The client generates the auth for the new server (gets a 403)
- The client generates v1 auth for the old server, sends it to the old server (gets 401)
- The client generates v0 auth for the old server, sends it to the old server (gets 401)

So it seems some combination of username/password is causing the v0.6 v1/v0 auth generation to fail. I'm not smelling any encoding issues because the user who reported says their password is pretty straightforward (AND it's in a pw manager, so no chance of mistyping). I'm also seeing in the logs a lot of 403/new followed by 401+401/old, meaning others are having the same problem and just haven't reported it yet.

**Comment by orthecreedence** [comment]
Added a new release to help debug this:

- https://github.com/turtl/desktop/releases/v0.7.1-login-debug
- https://github.com/turtl/android/releases/v0.7.1-login-debug

If anyone is having this issue, open the app and on the login screen, hit "Trouble logging in?" then fill out the form and send the result.

**Comment by orthecreedence** [comment]
Just a FYI, the lowercase did not fix this issue for the user who reported it. Still waiting to hear back before I can really continue here.

**Comment by orthecreedence** [comment]
I am fully convinced this is just because people were using Framanotes and the servers are lost during upgrade. Added a page for this: https://turtlapp.com/docs/troubleshooting/logging-in/#custom-servers

**Comment by orthecreedence** [comment]
Spoke too soon! A user actually came back with a real live case of this. Looks like the password is being processed differently in js than in rust. Everything about this screams of an encoding issue. Trying to gather more info from the user.

**Comment by orthecreedence** [comment]
Confirmed this is working now. Case closed. Hooray.

**Comment by wadouk** [comment]
I had some "special characters" in my password so I can't succeed to make the migration of my account in a 0.7.2 app (on manjaro) I had to change account to email and change password with more basics characters to succeed to login to the app. (framanotes, web gui 0.4)
