### ISSUE TITLE
[Core-rs] Doesn't build in Ubuntu 16.04

### ISSUE THREAD

**Issue by cibersheep** [turtl/tracker#193]
I have followed the steps from Readme (building libsodium-1.0.16 as in note2).
I have installed OpenSSL 1.0.2g-1ubuntu4.13
When try to build, I get this error

```bash
   Compiling regex v0.1.80
error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
  --> /xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/string_cache-0.2.29/src/lib.rs:71:13
   |
71 |     pub use atom;
   |             ^^^^
   |
note: the macro is defined here
  --> /xxx/core-rs/target/debug/build/string_cache-17bb1368184f623e/out/atom_macro.rs:2:1
   |
2  | / macro_rules! atom {
3  | | ("sdev") => { $crate::Atom { unsafe_data: 0x2 } };
4  | | ("onstart") => { $crate::Atom { unsafe_data: 0x100000002 } };
5  | | ("overflow") => { $crate::Atom { unsafe_data: 0x200000002 } };
...  |
127| | ("stroke-miterlimit") => { $crate::Atom { unsafe_data: 0x4f400000002 } };
127| | }
   | |_^

error: aborting due to previous error

error: Could not compile `string_cache`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by orthecreedence** [comment]
Weird, it's trying to load regex version `0.1.88` but the tom/lock file call for `0.1.77`/`0.1.80`. Are you using the same `Cargo.toml`/`Cargo.lock` file from the git tree? Also, what version of rust/cargo are you on?

**Comment by cibersheep** [comment]
> Are you using the same `Cargo.toml`/`Cargo.lock` file from the git tree?

I did a `git pull` before building. And doubled checked that I have the latest versions.

> Also, what version of rust/cargo are you on?

cargo 1.29.0-nightly (6a7672ef5 2018-08-14)

rustc 1.30.0-nightly (33b923fd4 2018-08-18)

Thanks

**Comment by cibersheep** [comment]
For the record:

- I have updated Rust `rustup self update`
- Then, `cargo update`
- `cargo build` is compiling the ¿correct? regex version but if fails again to build:

```rust
   Compiling regex v0.1.80
error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
  --> /home/cibersheep/.cargo/registry/src/github.com-1ecc6299db9ec823/string_cache-0.2.29/src/lib.rs:71:13
   |
71 |     pub use atom;
   |             ^^^^
   |
note: the macro is defined here
  --> /home/cibersheep/Ubuntu_Touch_Projects/Turtl_App/core-rs/target/debug/build/string_cache-a775b0d14fa82a8f/out/atom_macro.rs:2:1
   |
2  | / macro_rules! atom {
3  | | ("edge") => { $crate::Atom { unsafe_data: 0x2 } };
4  | | ("ondragstart") => { $crate::Atom { unsafe_data: 0x100000002 } };
5  | | ("keypress") => { $crate::Atom { unsafe_data: 0x200000002 } };
...  |
127| | ("aria-haspopup") => { $crate::Atom { unsafe_data: 0x4f400000002 } };
127| | }
   | |_^

error: aborting due to previous error

error: Could not compile `string_cache`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by cibersheep** [comment]
I just found this that might or might not be related
https://github.com/rust-lang/rfcs/blame/master/text/0453-macro-reform.md#L105

**Comment by orthecreedence** [comment]
All of our builds are on `rustc 1.27.1 (5f2b325f6 2018-07-07)` (or `1.28.0` for our automated build). I wonder if the nightly is what is throwing things off.

**Comment by cibersheep** [comment]
Ha! Well spotted!
I didn't know about Rust channels.
`rustup default stable` to change the channel to stable (`cargo 1.29.0 (524a578d7 2018-08-05)` and `rustc 1.29.1 (b801ae664 2018-09-20)`) and problem solved.
Thank you!

**Comment by orthecreedence** [comment]
Perfect! Glad it's working!
