### ISSUE TITLE
Migration freezing/hanging

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#201]
Seems migration is hanging after completion for some users.

(this was moved from issue #192)

**Comment by orthecreedence** [comment]
@dogfuntom would you mind looking if there are any other types of errors in the log besides files failing to download? I wonder if something else is blocking the migration.

**Comment by dogfuntom** [comment]
Okay, here's a full log then:
[core.log](https://github.com/turtl/tracker/files/2467037/core.log)

**Comment by orthecreedence** [comment]
So it looks like the migration did not get stuck on file downloads but seems to stop abruptly midway. Does the app crash for you when you try the migration? It looks like from the log it was attempted several times.

Do you know if you're on v0.7.0 or v0.7.1? 0.7.0 had an issue with the migration crashing that was fixed in 0.7.1. Might be worth checking!

**Comment by orthecreedence** [comment]
Oh sorry, you mentioned the migration just sat there. That's really weird, sounds like it froze, which might be an entirely different issue.

Do you mind installing this build of Turtl: https://github.com/turtl/desktop/releases/tag/v0.7.1-logfix

Then edit `c:\Program Files\Turtl\resources\app\build\config.yaml` and set

```yaml
...
logging:
  level: 'debug'    # <-- change this from 'info' to 'debug'
...
```

and trying the migration again? Thanks!

**Comment by dogfuntom** [comment]
Indeed, the nice recently added UI shows that download is complete but decryption goes until 50% and then does nothing.

[core.log](https://github.com/turtl/tracker/files/2472876/core.log)

**Comment by orthecreedence** [comment]
@dogfuntom Thanks for your patience. I've been picking through this as I have time. There's nothing conclusive in the log, unfortunately.

Looks like 226 items were decrypted, out of a total of 394 (so the 50% mark you were shown makes sense). Oddly, you have 191 keychains, 28 boards, so that's 219 items right there (those are done before notes) and it looks like the 8th note is the one that freezes it. I'm adding even more logging now to help narrow this down, hopefully it at least points to a specific item/place I can start looking more carefully.

Anyway, here it is: https://github.com/turtl/desktop/releases/tag/v0.7.1-migration-logging

**Comment by orthecreedence** [comment]
Oh, forgot to mention, can you change `log.level` to `"trace"` in `config.yaml`?

```yaml
...
logging:
  level: 'trace'
...
```

**Comment by dogfuntom** [comment]
I can't find the log where I got it previously (`%AppData%\Roaming\Turtl\core`). Where is it?

**Comment by orthecreedence** [comment]
@dogfuntom Hmm that's weird, it should be there. If you delete the contents of `%AppData%\Roaming\Turtl\` and start Turtl again, does it show up?

**Comment by dogfuntom** [comment]
It does:
[core.log](core.log)

**Comment by orthecreedence** [comment]
@dogfuntom this is helping to narrow things down. Do you also have any other core log files in that folder, like `core.log.1` or `core.log.2`?

**Comment by orthecreedence** [comment]
Ok, actually this is spookily similar to another issue I saw on another bug. Essentially, the core request was panicking and because of a bug in the way commands are sent to the core, it wasn't catching the panic and it looked like it was hanging when really it had stopped because it had a failure and didn't tell anyone.

@dogfuntom I hate to do this to you again, but can you replace `C:\Program Files\Turtl\resources\app\build\turtl_core.dll` with the DLL in this zip:

[turtl_core.zip](https://github.com/turtl/tracker/files/2517318/turtl_core.zip)

And give it another shot? I'm betting it will actually spit an error message out this time, and if not, send me the log again.

Once again, thank you very much for helping me work through this issue. I think we're getting close.

**Comment by dogfuntom** [comment]
Here's the error and more logs:
![5](https://user-images.githubusercontent.com/905138/47622274-6085a400-db14-11e8-877e-1f5976d41d7d.png)
[core.log](https://github.com/turtl/tracker/files/2523262/core.log)
[core.log.1.txt](https://github.com/turtl/tracker/files/2523265/core.log.1.txt)
[core.log.2.txt](https://github.com/turtl/tracker/files/2523266/core.log.2.txt)

**Comment by orthecreedence** [comment]
Thanks! I finally found it. Apparently you have a file with the raw contents of 

```javascript
[object Object]
```

Which is what happens if you convert an object to a string in Javascript:

```javascript
var my_object = {name: 'andrew'};
console.log(my_object.toString());    // prints "[object Object]"
```

So this file is supposed to have a full set of ciphertext in it (650256 bytes to be exact) but because of some bug in the older version of Turtl, it was not uploaded properly. When the new version of Turtl tries to "decrypt" that file, it fails to deserialize because it's expecting encrypted binary data and instead gets `[object Object]`.

The bad news first: This file is likely not recoverable and probably gone forever. If you know which file it might be and you happen to have an old version of Turtl still installed, you might be able to download it from the local data. Looks like it was uploaded March 26, 2017 (if that helps narrow it down).

The good news: I can easily fix this now that I know where the problem is and get you on the latest version of Turtl (which has not had any issues uploading files).

**Comment by orthecreedence** [comment]
@dogfuntom Can you try 0.7.2? https://github.com/turtl/desktop/releases/tag/v0.7.2

This should hopefully fix the issue! Thanks!
