### ISSUE TITLE
Turtl Android => Building/running => Docs coming soon.

### ISSUE THREAD

**Issue by Tom3141** [turtl/tracker#210]
I managed to get Turtl libraries to build (ref: https://github.com/turtl/tracker/issues/157 ) 
I'm trying to figure out how to build/run and install it on my android phone:
When I look https://github.com/turtl/android/blob/master/README.md#buildingrunning
all it currently says is:
> Building/running
> 
> Docs coming soon.
I noticed there is some info in history:
https://github.com/turtl/android/commits/master/README.md that has been apparently been removed.

Any chance you guys have a current set of work instructions that can save me some time figuring this out?

**Comment by orthecreedence** [comment]
Sure. The Android app uses Cordova/the android SDK/node/npm to build, and assumes the following directory structure:

```
turtl/
    js/
    android/
```

It pulls the assets from the `js` project and uses them as the interface, and uses codrova for building the APK. Depending on the architecture of your phone, you'll have to compile the core for either armv7 or armv8 and put the resulting `libturtl_core.so` file into the proper place in `turtl/android/native/`:

```
turtl/
    android/
        native/
            arm64-v8a/        # <- put libturtl_core.so for armv8 here
            armeabi-v7a/      # <- put libturtl_core.so for armv7 here
```

Regarding building the core for specific platforms, if might be helpful to refer to the Turtl build on F-Droid: https://gitlab.com/Rudloff/fdroiddata/commit/a0fb62454c3c98aea19cb0641cd5d1fd74c568ad

The general android build instructions are as follows:

### One time setup

```sh
cd turtl/js/
npm install
cd ../android
npm install
cordova platform
```

I think that should do it.

### Building

```sh
make build
```

This builds a debug APK somewhere under `platform/android/` (I forget the exact location just search for it: `find . -name" *.apk"`).

I'm probably leaving out a few steps. Just reply and I'll try to give guidance where possible.

**Comment by mdaniel** [comment]
It would be awesome to at the very least update the readme to point to this issue, and then hopefully update it for real when Tom3141 confirms the steps behave as expected.

I got as far as trying to cross compile openssl before getting the sad-trombone, but I didn't think to check the f-droid manifest, so I'll give those steps a try

**Comment by rubbingalcoholic** [comment]
Updated the readme with this info.
https://github.com/turtl/android/commit/5d257b701e0980972ca9bf17032b8f1bc51ee41a
