### ISSUE TITLE
Feature request: Have an image note A embedded in another note displaying A's image

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#212]
Over the latest release v0.7.1-logfix.

I wanted to know if it is possible it have an imported image being displayed within a note over Turtl? Because I tried importing an image for this purpose, but I was unable to identify how to use this uploaded image inside an existing note. This would be very nice fro three initial reasons:
1. The linked image wouldn't has a link which latter could go offline.
2. The image reference is not external, thus preventing some short of infection from malware attached  images "referred" over notes latter in time.
3. User control is one of the aspects from UX which describes the user ability to control thoroughly the application's features.

**Comment by l4mbd0x** [comment]
https://github.com/tonyxu-io/tiny-url (Uses JS)
https://github.com/rmadrazo97/tinyUrl1 (Uses JS)

**Comment by orthecreedence** [comment]
I'm not fully understanding the feature request. Do you want the bookmarker to download/attach images to notes instead of linking to them?

**Comment by l4mbd0x** [comment]
Hm. Nah, I wanted to know if it is possible it have an imported image being displayed within a note over Turtl? Because I tried importing an image for this purpose, but I was unable to identify how to use this uploaded image inside an existing note.

**Comment by orthecreedence** [comment]
Do you mean something like:

```
Title: Note A
Attachment: image.jpg
```

```
Title: Note B
Body: Here is the image in Note A: [[Note A]]
```

where Note B embeds the image from Note A?

**Comment by l4mbd0x** [comment]
Sorry, if I wasn't clear about that I was looking for @orthecreedence.
Yes, that's precisely what I want.

**Comment by orthecreedence** [comment]
Ok, cool. I think this might fall under feature for linking between notes: #37

When referencing another note, it will show a preview of the note's content.

**Comment by l4mbd0x** [comment]
Ok, I'll reorganize this thread's description for future reference.

**Comment by orthecreedence** [comment]
I'm going to close this and add these notes to #37
