### ISSUE TITLE
Bookmarking extension not pairing after v0.7 client update

### ISSUE THREAD

**Issue by jlbrewer** [turtl/tracker#213]
Browser: Firefox 62.0.3
OS: Windows
Turtl: 0.71
Last bookmark extension update according to Firefox: Feb 18
Behavior: "Error Talking to Turtl 401 - needs pairing"

Cannot figure a way to force it to pair/refresh pairing data. I think 0.6x ran njws as a back-end process and that doesn't look true in the new version.

**Comment by orthecreedence** [comment]
Can you try removing the extension and reinstalling it? Sometimes it gets "stuck"

**Comment by jlbrewer** [comment]
Yeah, that made it behave (I had tried disabling-reinabling plus restarting browser and client).

**Comment by orthecreedence** [comment]
Good! Thanks for giving it a shot.
