### ISSUE TITLE
Feature suggestion: Mass moving/reorginization of notes between boards and/or spaces

### ISSUE THREAD

**Issue by jlbrewer** [turtl/tracker#214]
With the update to 0.7 the first thing I wanted to do was transfer my 'Imported' notes into the 'Home' space. Unless I missed something, the only way I could figure out was to move each individual board and then move all of my unsorted notes (about 20-30) into a temporary board and then move that board before resorting the notes to their proper place. (some were accidentally unsorted, some I swear I had sorted but weren't caught by the importer, some I had been just too lazy to define a board for).

I won't presuppose any best way of doing these sorts of tasks but I'm sure there are better ways than what exists. A more general use-case would be someone who wants to take a bunch of notes from their private 'home' space and transfer/copy them to a shared space.

So, to try to itemize it (I'll probably miss things):

- The ability to mass-select groups of notes (regardless of how they are currently sorted)
- The ability to chose to move or copy those notes to new spaces in a single action
- The ability to bulk-assign notes to a board.
- The ability to move individual notes that haven't been assigned to a board (and/or a default 'unsorted' board for them to belong to)
- While at it, include the ability to mass-delete and any other operations that are standard to this sort of thing.

**Comment by orthecreedence** [comment]
Agreed, this would be a great feature! This is tracked in the "Batch note editing" feature: #41 so for now I'm closing this as a dupe
