### ISSUE TITLE
Can't pair browser plugin/extension (Chrome/Firefox/etc) with desktop

### ISSUE THREAD

**Issue by mutagenfork** [turtl/tracker#218]
Browser: Chromium ( Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)]
OS:  Gallium (Ubuntu derivative for Chromebooks)

When I click on the Turtl plugin, I get a popup asking me to sync the Desktop app with the extension by entering a pairing code into the extension.  However, only 1 time out 3 does the extension popup window appear where I could paste the pairing code.  And when it does appear, it disappears as soon as I click on it, before I can paste the pairing code.  

If it's not easy to fix the popup window behavior, maybe put the pairing form on the details page for the extension?  

This window appears every time I click on the plugin icon:

https://imgur.com/P7RKWz0

This popup appears on 1 out of 3 times when I click on the plugin icon.  However, it disappears immediately when I click on it, before I can paste the pairing code into the field:

http://i.imgur.com/0KGRWyF.png

**Comment by orthecreedence** [comment]
Yeah, this is a major annoyance on both FF and chrome...they both handle the popup window frustratingly bad. It might make sense to just open a new tab with a text box in it. This is a good suggestion. Thanks.

**Comment by KennyJolt** [comment]
I found a workaround for Turtl to force the extension pairing popup and persistence so that the pairing code can be entered.

Right click the Turtl extension icon > Select **Inspect popup** menu item > paste the paring code into the popup.

This worked in Brave browser beta and should work the same in other browsers that are Turtl extension compatible.

**Comment by orthecreedence** [comment]
Thanks, Kenny. I'll suggest that to people who have this problem until there's a more permanent fix.

**Comment by dan-osul** [comment]
Just adding that you will need to install the Chrome Apps & Extensions Developer Tool for the inspect popup option to appear if you are using Chrome/Chromium.

**Comment by daviewales** [comment]
I don't think the workaround works for Firefox.

**Comment by orthecreedence** [comment]
Going to mark this as closed for now. The extension now opens a pairing tab instead of a popup, which should make pairing much more painless. The new extensions are publishing in the chrome/ff stores as I write this.

If anyone does have further problems, this issue can be re-opened.
