### ISSUE TITLE
Loosing data at import

### ISSUE THREAD

**Issue by opensource21** [turtl/tracker#226]
Tried to migrate data at linux 64 bit with 0.7.1. The migration seemed to work, but I have the following problems.
At one shared board a note is missing
At a second shared board to Notes which only have a headline are missing.

At nested board a lot of notes are lost.
The structure was 
G
and G/P
I tried to put all notes of G/P to G too. G should contains some notes which are only at G not at G/P. All boards are private ones.

program | In G via overview | In G/P via overview | In G via search | In G/P via search
-----------|------------------------|--------------------------|--------------------|--------------------------
old turtl desktop |100|84|84|84
old turtl android |50|84|84|84
new turtl desktop |-|-|36|48

via Overview means: I looked at board overview
via search means: I choose the board and open the search view

Before I make the measurement I delete all local data at android and linux (which changed unfortunately the numbers, so I hope that I didn't loose note before.

Summary: After delete local data at least the number of entries in G + entries in G/P in search seems correct. 

How could I analyze it with out checking each entry?
Why there is one Entry missing on the shared board?
Why are notes with no contents are lost?

**Comment by orthecreedence** [comment]
The migration doesn't move shares, and it only moves data you own. So if you have a shared board with someone on the old version of Turtl, only the notes that you created in that shared board would be moved. This is a conscious decision so that only data you own gets migrated, and when the other people the baord is shared with migrated, they bring their data (and none is duplicated).

One thing I realized though is that migration also skips copying over boards that you aren't the owner of. This orphan the notes in that board.

This is something I can fix.

**Comment by orthecreedence** [comment]
Oh, one thing that can help me track down and make sure there's nothing else going on is if you go to the menu -> Settings -> Debug log, select "load everything" and send me the contents.

**Comment by opensource21** [comment]
Okay that explain the one missing note. And perhaps the two which only have a headline.
The situation at the g and g/p board I still not understand and don't know how to fix it quickly. I would expected that all notes which are in G and G/P are at the end of migration in G/P. Hopefully no data are lost.

Attached the log hope that it helps

[turtl.log](https://github.com/turtl/tracker/files/2536115/turtl.log)

**Comment by orthecreedence** [comment]
Hi, I'm not seeing any failed items in your migration. Also, I released a new update that will preserve shared boards when migrating (although notes still only migrate if they were created by you):

https://github.com/turtl/desktop/releases/tag/v0.7.2.2
https://github.com/turtl/android/releases/tag/v0.7.2.2

You would have to delete your account and migrate again to make use of this change, unfortunately, but it might be worth it depending on how much new data you have in the account. Keep in mind you can use the new export feature to preserve data as well.

I think I am going to close this issue for now. If you have any other issues migrating please let me know and we can re-open.
