### ISSUE TITLE
Publish android to F-Droid

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#23]
This should be easy(ish) now that we've dropped XWalk.

**Comment by eternaltyro** [comment]
Yes, publishing this on F-Droid will definitely increase visibility. I used to use Turtl ages ago. Now that it's being actively developed, it's better to publish even beta quality app releases to F-Droid. That way, more people will test it.

**Comment by eternaltyro** [comment]
Apparently, being a cordova app is a problem for building on F-Droid: https://gitlab.com/fdroid/rfp/issues/412

**Comment by eternaltyro** [comment]
Also, there's a repo just for F-Droid here but it does not seem to have been updated in the past two years: https://github.com/turtl/fdroid

**Comment by Rudloff** [comment]
> Apparently, being a cordova app is a problem for building on F-Droid

To clarify, it is not really a problem. It's just that it is a lot easier for us to package the app if the Android project generated by Cordova (usually in `platforms/android/`) is published in the repository.

**Comment by orthecreedence** [comment]
I can easily revive the [turtl/fdroid](https://github.com/turtl/fdroid) repo in the build process. I've been really busy with the v0.7.0 release and haven't had time to do this yet. Since it's fairly easy, I'll add it to the v0.7.0 milestone.

**Comment by orthecreedence** [comment]
@Rudloff actually, I just realized that the android app (as of v0.7.0) bundles two `.so` files, which are compiled versions of the [core](https://github.com/turtl/core-rs). This probably complicates things. I think I'm going to move this discussion to the gitlab issue: https://gitlab.com/fdroid/rfp/issues/412

**Comment by orthecreedence** [comment]
The app is building on F-Droid and now awaiting merge. I think at this point, the issue can be considered completed. If there are any problems further on, we can re-open this.
