### ISSUE TITLE
Allow trusting self-signed certificates

### ISSUE THREAD

**Issue by marcb1** [turtl/tracker#235]
Currently the turtl desktop client does not trust self-signed certificates. This would be useful to have for running the turtl server on a separate server, using reverse SSL proxy with a self signed cert.

**Comment by orthecreedence** [comment]
Completely agree.

**Comment by orthecreedence** [comment]
closed via https://github.com/turtl/js/commit/2fa3bc19208eb609f3fe5a9d97d28f0ea4e8538d
