### ISSUE TITLE
Control/Cmd+S for save from within note edit view

### ISSUE THREAD

**Issue by benbailess** [turtl/tracker#236]
I'm requesting a feature to be added to support using control + s (on Linux or Windows) and cmd + s (on mac os) to save the current note when in the note edit view. Thanks for making a great note taking application!

**Comment by orthecreedence** [comment]
Hello, thanks for the suggestion! This likely won't be implemented for two reasons:

- We are going to have auto-save very shortly: #152 
- You can already save from the note editor using Ctrl+enter / cmd+return!
