### ISSUE TITLE
Login Username should be marked as e-mail-field

### ISSUE THREAD

**Issue by opensource21** [turtl/tracker#238]
At the moment I have in combination with swiftkey 2 issues:

- If I write a Dot which isn't unusual for E-Mail I get a whitspace after it. 
- At the end I get a tailing blank, which end in a unknown user. 

I guess both can be fixed if it marked as an E-Mail-Field oder password-field

**Comment by opensource21** [comment]
Should be 

`<input type="email" name="username" placeholder="{{t 'Email'}}" value="{{state.last_username}}" tabindex="1" autocomplete="off" autocorrect="off" autocapitalize="off">`

in https://github.com/turtl/js/blob/master/views/users/login.hbs line 1. 

I seems that `autocomplete="off" autocorrect="off" autocapitalize="off"`has no effect.

**Comment by betsythefc** [comment]
@opensource21, I've submitted a pull request with you recommended changes.

**Comment by orthecreedence** [comment]
Wait, actually, I just realized...

Turtl v0.6 logins do not need to be emails, so enforcing `type="email"` on the input field would break many migrations. I think we need to keep it as-is for now.

**Comment by orthecreedence** [comment]
Ok, I just pushed a fix for this. I am setting `<input type="email" ...>` and also setting `<form ... novalidate>` which seems to respect the email input type without throwing an error if it's not an email.
