### ISSUE TITLE
The new server does not send e-mails

### ISSUE THREAD

**Issue by darthmooguy** [turtl/tracker#239]
I have set-up the new server in NodeJS. I have followed all the steps in the setup section and I have it up-and-running. However, the server does not send out confirmation emails to the users. Consequently, they cannot invite other users to their spaces.

Am I missing some config? I noticed that the email sending is done through the plugins, but my plugins dir is empty.

Thanks!

**Comment by orthecreedence** [comment]
Hi, I've added an [example plugins folder](https://github.com/turtl/server/tree/master/example-plugins) to the server.

This has a working email plugin example, and see the updated `plugins` section of [config.yaml.default](https://github.com/turtl/server/blob/master/config/config.yaml.default#L44) for a quick note on configuring.

Note that you'll have to either move the `email/` folder (and the `package.json` file next to it) from `example-plugins/` to `plugins/`, or set `plugins.plugin_location` to the path to `example-plugins/` to get it running. Also, wherever you decide to place the plugin, you'll have to run `npm install` inside the directory it's in.

If you need something with more power, like mailgun, you can easily adapt the email plugin to do this!

I'm going to close this issue for now, but feel free to ask questions if you get stuck and I'll respond.

**Comment by darthmooguy** [comment]
Hi, thanks for the quick response! I have set up the email plugin and it now works as expected. Thanks!
