### ISSUE TITLE
Server - Windows

### ISSUE THREAD

**Issue by Outi-s** [turtl/tracker#240]
Hello, thanks for all the hard work.

I have been using Turtl for a while now. However I have been looking into some wiki type apps and came across [DokuWiki](https://www.dokuwiki.org), they have this wonderful [DokuWiki on a stick](https://download.dokuwiki.org) feature which comes with a MicroApache Web Server.

I was wondering if something like this is possible for Turtl Server. Or if something can be cooked up with [XAMPP](https://www.apachefriends.org/index.html).  When we are out or if the system is turned off, things can be synced when back.

If there is currently a way to do this, can someone please add the instructions to the Readme file.

Thank you.

[On Windows 10 Pro]
[Minimal to no idea of php or db files but can follow instructions]

**Comment by orthecreedence** [comment]
This is a great idea. However, it would be tricky. DokiWiki appears to not need a database (it uses SQLite which is very portable) and the Turtl server does use a database (Postgres). That's not to say it's impossible to create a portable version of the server/database, but there are some unknowns there that might cause problems, and it would complicate the packaging of the server (it would need a windows/osx/linux portable version for each release, and right now it doesn't need these at all).

I think this may be something that would be handled as a community effort outside of the project itself.

For now, I'm going to close this issue, but feel free to asking any questions or give suggestions and I'll respond.

**Comment by Outi-s** [comment]
Thank you @orthecreedence.

**Comment by Outi-s** [comment]
@orthecreedence, sorry for bothering you but how about [this project on GitHub](https://github.com/garethflowers/postgresql-portable) or maybe [this](http://www.postgresonline.com/article_pfriendly/57.html).

Also, can't just the necessary files be updated? If the base files are the same, some edits and stuff can be followed by even the most beginners of us.

**Comment by orthecreedence** [comment]
Those projects certainly look like they would make this easier.

Here's the thing, this might be an easy project, or it might be more complicated. I don't know yet. But if I include it as a feature of the server itself, then I have to maintain it, and not just on one platform, but on three different platforms. Right now, it's mainly just me working on Turtl, and there's a lot of maintenance already. I'm cautious about adding more to my plate.

A portable version of the Turtl server is something that someone who has knowledge of how to run a node/postgres app could make and maintain in their spare time. If someone were to take this on, I would happily link to their project from the server page and the website. However, at this point I can't really take on more maintenance than I already have.

**Comment by Outi-s** [comment]
Thank you @orthecreedence for the reply and the hard work.
