### ISSUE TITLE
board not showing all notes

### ISSUE THREAD

**Issue by popindavibe** [turtl/tracker#247]
Hello,
I have successfully migrated to the new client/server, however I just noticed a strange issue on the new client (v7.2.3).

When I open my meta-board (board gathering smaller boards) it only shows the notes for that specific board **only**, while from the navigation bar and total size of the pane makes me believe that all other notes that belong to sub-boards (and by extension to this meta-board) **should** be displayed as well but for some reason are not.

**Comment by Outi-s** [comment]
Under a Space, All Notes show all the notes in all the other boards. I don't think you can see all notes in all workspaces all at once. Though it is possible I might be missing something.

**Comment by popindavibe** [comment]
Sorry if I was not clear. I have no issue with the Space itself, all my notes are in the 'Imported' space and they all show (there is a `Next` link to go to the next page).

The problem is only related to board / sub-boards within a space.

For example,:
- _IT_ board containing notes belonging only to this board
  - a sub-board called _test_ (showing as _'T/test_)
  - another sub-board called _prod_ (showing as _IT/prod_)

In the previous version of the desktop client I would be able to see notes for IT + IT/test + IT/prod when selecting IT board. In current version it only shows notes for IT only.

Did the import flattened all sub-boards into stand-alone boards? (in which case _IT/test_ would just be a board name now) 
Is it not a feature any more?

**Comment by Outi-s** [comment]
I don't think there are sub-boards anymore. I'd just rename them so:
```
IT
IT > Test
IT > Prod
```
So, they at least retain their place.

Again, there is a chance I might be missing something.

**Comment by popindavibe** [comment]
Ok, I have move my 'meta-board' into its own space and further move the sub-boards into that space, so that I end up having the same kind of setup fitting the new format.
