### ISSUE TITLE
Android app shares images as attachments

### ISSUE THREAD

**Issue by maxf** [turtl/tracker#252]
When sharing a picture (from the Gallery app, for instance) it's save to turtl as an attachment note and not as an image note. This prevents the picture to be previewed on the board page.

**Comment by orthecreedence** [comment]
Thanks, I just updated the "share to Turtl" feature in v0.7.2.4 but sounds like it still has some glitches. I will check this out.

**Comment by orthecreedence** [comment]
Note that this was just fixed along with #271 and will release in v0.7.2.6!
