### ISSUE TITLE
Files not migrated

### ISSUE THREAD

**Issue by mat-m** [turtl/tracker#259]
Hello

I did not notice the upgrade path. Yesterday I wanted to reach my data, so I just follow the migration path. All notes seems migrated, but files were not. 'File' and 'Image' type of notes are impacted.

The migration occurred on the Android client. Maybe I had not enough bandwidth to proceed. I actually don't remember if an error was shown( Didn't seem to, but if it was a timed pop-up, I could have missed it)

Is there a way to trigger the migration again ? Or to catch it back ?
It was not on turtlapp.com but on framanotes.org

**Comment by orthecreedence** [comment]
Hello! Try deleting the account (Settings -> Delete my account) and then you should be able to try the migration process again.

**Comment by mat-m** [comment]
OK, delete and migrate again solved it.

Thanks

**Comment by orthecreedence** [comment]
Great! thanks for reporting back.
