### ISSUE TITLE
Error after doing ./scripts/init-db.sh on ubuntu 16

### ISSUE THREAD

**Issue by sorcer1122** [turtl/tracker#264]
Hello,

After ./scripts/init-db.sh command I get the following error:

- running DB schema
/root/turtl/node_modules/pg/lib/connection.js:123
      self.emit(msg.name, msg)
                    ^

TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (/root/turtl/node_modules/pg/lib/connection.js:123:21)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)

Any idea where to dig to fix it? Thanks

**Comment by orthecreedence** [comment]
Did you update your `config/config.yaml` file to point at your DB?

**Comment by sorcer1122** [comment]
Yes, I did. Used ubuntu's mysql, pointed out config.yaml to 127.0.0.1, port 3306 and included username with password and DB name.

**Comment by sorcer1122** [comment]
Yes, I did. Used both files here as templates - https://github.com/turtl/server/tree/master/config but still no luck. I am using MySQL that came with Ubuntu. Or do I need to get Postgres instead?

**Comment by orthecreedence** [comment]
Yes, Postgres is required. Please see this page: https://github.com/turtl/server#running-the-server
