### ISSUE TITLE
Share to Turtl from browser should create a bookmark, not a file

### ISSUE THREAD

**Issue by oskarsh** [turtl/tracker#271]
If you want to share a website with the Turtl app to let it get saved as a Bookmark it saves it as a File. You need to manually add a Bookmark and paste in the Link. 
I think the Default action for sharing Links with the Turtl app should be to save it as a Bookmark.

**Comment by orthecreedence** [comment]
Agreed, thanks for the feedback!

**Comment by rhein** [comment]
Just as a side-note, for me turtle v.07.2.5 (from f-droid) does create bookmarks when sharing from Firefox, Fennec or standard android browser.

**Comment by orthecreedence** [comment]
Seems like this is only an issue with Chrome. It's sending some wacky data in.

**Comment by orthecreedence** [comment]
Ok, this should be fixed and will release in v0.7.2.6
