### ISSUE TITLE
Plugins in Android

### ISSUE THREAD

**Issue by dayfuaim** [turtl/tracker#277]
Will plugins appear in Android build?
When will it happen?

They are _very much_ needed, without them sync is purposeless as you cannot see what you typed at desktop (I mean tables and such).

**Comment by orthecreedence** [comment]
I don't understand what you mean by plugins. Can you clarify?

**Comment by dayfuaim** [comment]
OK.
I mean this:
![2019-01-27 02 23 39](https://user-images.githubusercontent.com/1274699/51793996-9cdfa380-21da-11e9-8d67-c866fbd157cf.png)
Some of them are bundled, some are installed via `ipm`.

**Comment by orthecreedence** [comment]
We will probably never have third-party plugins. I actually love the idea of people being able to extend the app, but then having to support something being broken by a poorly written plugin sounds like a nightmare and would make determining problems in Turtl 10x harder. On top of this, plugins would be a *huge* security problem. If the app lets anybody plug in some random code, who's to say it wouldn't be sending your private data off to some malicious third-party server?

Privacy is probably the main concern of this app, and plugins would greatly increase the attack surface.

**Comment by janedough1331** [comment]
I think you should reconsider this. Lots of security apps allow plugins. Like KeePass2 for example allows plugins. Plugins would be open source, just like Turtl is, so it would be easily verifiable that they aren't up to something sketchy. And it's not up to you to make sure that a developers _plugin_ doesn't break things. People will realize "Hey this was working yesterday, before I installed a plug in." Standard Notes allows plugins, and I would love to see you + Turtl be a strong competitor for Standard Notes.

EDIT: My bad. I'm not 100% sure but from my understanding Standard Notes "plugins" come in the form of paid extensions... Which would explain why its worth the "extra work" you speak of. But with that said, I still stand by my statement that app breakage is up to the plugin developer. You could even have yourself, or the community, verify the code and list it on the Turtl website, or github, as a "verified plugin" once the code has been reviewed.
