### ISSUE TITLE
f-Droid "issues" directs to /fdroid/pulls and not /tracker/issues

### ISSUE THREAD

**Issue by Brassfield** [turtl/tracker#278]
F-Droid > Turtl > Links > Issues

Link directs to https://github.com/turtl/fdroid/pulls

Should direct to: https://github.com/turtl/tracker/issues

**Comment by dadosch** [comment]
Merge Request on F-Droid's gitlab repo done: https://gitlab.com/fdroid/fdroiddata/merge_requests/4377

**Comment by orthecreedence** [comment]
Thanks!

**Comment by dadosch** [comment]
Can be closed now.
