### ISSUE TITLE
Right-clic menu is not available anymore

### ISSUE THREAD

**Issue by Ra0EL** [turtl/tracker#280]
Hi,
in Turtl version `<0.7`, in Linux or Windows, I was used to right-click to open the "Inspect..." item (Dev tools). This was a valuable workaround to set **my own CSS theme** in Turtl.
Unfortunately this is not available anymore in new clients :disappointed: 

Any chance to recover this feature ?
(or hurry up with availability of themes in Turtl :wink: )

_IMHO, this is a must have. At least because your H1/H2/H3 headers are not distinguishable at a glance :smile: _

**Comment by Outi-s** [comment]
`<style>` tags work with Turtl.

**Comment by orthecreedence** [comment]
Use `ctrl+shift+k` to open dev tools in the new Turtl (or cmd+shift+k I believe in OSx).
