### ISSUE TITLE
web site does not work

### ISSUE THREAD

**Issue by aTanW** [turtl/tracker#285]
I done instrutions in js's README, "npm install" completed w/o errors, webserver apache2.4, https configured.
Browser shows page with black bar at page top, Turtl logo, word "Turtl" on it. Nothing more.

What wrong?

**Comment by orthecreedence** [comment]
The problem is that, unfortunately, the frontend isn't built to run in a browser (yet). We need to complete #52 before this is possible, which is an ongoing goal. Until then, the frontend has to be packaged in a desktop/mobile platform.

**Comment by aTanW** [comment]
Sorry, I not found #52. And thank you for working on this goal.
