### ISSUE TITLE
Server: self-hosted www_url

### ISSUE THREAD

**Issue by aTanW** [turtl/tracker#290]
Sorry, but I cannot find any information about correct setting for this config item.

Problem in email ack and invites.

When I set it to the same value as api_url, it does not confirm email from link in email message.

**Comment by rhein** [comment]
for me it works with this set to the same value as api_url. What is the error you get?

**Comment by orthecreedence** [comment]
Email confirmations use the `api_url` value, and then redirect to `www_url`. So if `api_url` is set correctly (to the URL users would connect to via the "Turtl server" URL in the app) then it's possible your users *are* being confirmed, but are being redirected to a nonexistent page afterwords.

You'll want to set `www_url` to a website that has the following pages:
- `/users/confirm/success/` - a successful confirmation
- `/users/confirm/error/` - a problem with confirmation (`?err=<error message>` will be defined)
- `/users/delete/success/` - when a user is successfully deleted
- `/users/delete/error/` - when a deletion results in error (`?err=<error message>` will be defined)

**Comment by xuze1993** [comment]
I just left it blank and its ok.
