### ISSUE TITLE
Server and web interface / Disable signups / Restore attachments

### ISSUE THREAD

**Issue by vitobotta** [turtl/tracker#299]
Hi, I have just got Turtl server set up and I like it. :) 

I must admit that I have spent some time trying to get a web interface to work... because I was getting a bad auth message in the logs. I then tried to connect with the macOS client and lol it worked, I could create an account and add notes etc.

Questions:

1 - Am I missing something or a web interface is completely missing in Turtl server? Is this supposed to be used only with desktop/mobile clients? From what I've read so far this isn't clear to me...

2 - I don't want others to be able to sign up with my instance, so after creating my account I updated the Nginx virtual host to deny any requests other than GETs to /users. It works, but I was wondering whether there is a more elegant way?

3 - Attachments are uploaded correctly to S3 (actually Wasabi). But if I drop notes containing attachments and then I restore a Postgres backup, of course I get back only the notes without attachments. Is it on the roadmap to add some sort of "Trash" so notes and attachments do not get deleted permanently right away when user deletes them? So that it would be possible to recover attachments as well within a certain amount of time.

Thanks in advance!

**Comment by vitobotta** [comment]
I forgot another thing: why does the mac client ask me to accept incoming connections?

**Comment by Aphris-Karu** [comment]
Im seeing the same thing and was wondering if there was a web interface. Your right that it is not clear.

**Comment by orthecreedence** [comment]
Hello!

1. There is no pure web interface. This is a high priority (#52, #246)
2. There is a tracker for this (#250) however in the meantime, edit `server/helpers/auth.js` and remove `'post /users'` line from the `public_routes` array.
3. Not yet, but tracked (#251)

**Comment by orthecreedence** [comment]
Oh, regarding incoming connections on the app, the desktop app opens an HTTP server that the bookmarker extension talks to. If you don't use the bookmarking extension, you can safely block the incoming connections.
