### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by xuze1993** [turtl/tracker#300]
I've tried several wiki and note  apps recently,and i think turtl is the topest in concise and sync.(leanote and triliumnotes  functional  somehow)
There're some cons to me while i am not capable with codes.
1.It seems that i cant upload serveral attachments once.
2.Will it be possible that the notes on board have their own child path  other than just groups?
3.Notes marking their update time seems more orgenized,seaching able better.
4.Since satety is not so important with a self-hosted service ,a web-page would be of more convenience.

**Comment by orthecreedence** [comment]
Thanks for the suggestions!

1. This will probably not happen because it's technically a large change.
2. Possibly, but we've never had more than two levels.
3. Notes do mark their create time and update time, and this can be sorted using the "Search" icon.
4. This is coming soon!
