### ISSUE TITLE
Restore postgresql backup

### ISSUE THREAD

**Issue by vitobotta** [turtl/tracker#301]
Hi, I am testing backups and restores in case something happens etc.

I am trying to restore a backup but it looks like the client apps (both mac and Android) push their version of the data back to the server, basically overwriting the data restored on the server.

What is the correct procedure for a successful backup/restore?

Thanks!

**Comment by orthecreedence** [comment]
Hi, I'm not sure if I already answered this on Reddit, but just for documentation purposes I'll do so here too. The procedure to restore would be:

1. On both clients, open the settings and select "Clear local data."
1. Do not log back in on any clients yet, leave them in a logged out state.
1. Restore the postgres DB.
1. Now you can log in as needed.

Now that I think about it, restoring the database and then just doing "Clear local data" on the client should work, but the above will definitely do a full restore.

**Comment by vitobotta** [comment]
Hi, sorry for the delay - just noticed the notification of your reply. Yes, you answered on Reddit too - it works. Thanks! :)
