### ISSUE TITLE
RFE: Add markdown behavior preferences to Settings menu

### ISSUE THREAD

**Issue by taw00** [turtl/tracker#303]
Turtl's markdown does not follow standard markdown behavior (commonmark or daring fireball markdown) in regards how it treats new lines. By default Turtl is configured to treat new lines in the markup as hard line breaks once rendered. This behavior is inconsistent with other editors and renderers and the standard (portability and usability issue IMHO) and is cause for some bizarre and challenging rendering.
```
Here's my paragraph, **HMM!** and I [have a link here](http://example.com/XXXXXXXXXXXXXXXXXXXXXXXXXXXX)
where is the right place to add a line feed now since the renderer will do unexpected
things if I don't leave this as one giant line...
```
Folks already have to do things like configure links like above. Learning to toss in a <br /> or two spaces is simply not that much of a stretch. And if they have ever done any markdown or html in the past, the behavior is easily understandable.

I think this is the only ugly issue. But, apparently some folks like the "all line breaks are hard line breaks" configuration. Who are you people!?! ;)

Fortunately, `markdown-it` (the library that does all this) is easily configured to function either way. The js/main.js file contains "breaks: true" which can simply be set to "breaks: false". Well... this gets moved to `<turtl path>/resources/app/build/app/main.js` after everything is built.

Now we just need this configurable in the Settings menu. I have attempted to grok the code surrounding this menu, and it is a bit opaque to me. But... to be frank, if the decision is to, by default, have that set to something non-standard I think it then deserves a Settings menu section. Call it Settings > Markdown (or some such).

Note: I am not trying to make this a religious issue. I just wanted to make my point as clearly as possible. Related: https://github.com/turtl/tracker/issues/162#issuecomment-471309024

**Comment by Outi-s** [comment]
I like the way Turtl handles line breaks. I'm the people.

While yes, it kind of breaks down the text flow in markdown apps. It works wonders in others. I use both Joplin & Turtl and both use the same line break strategy. Though, yes, Joplin does support both kind of line breaks, the normal ones and the double space ones.

**Comment by taw00** [comment]
All the more reason it really needs to be a configurable option. The starting point should always be "the standard" and anything that deviates really should be a configuration option.

**Comment by orthecreedence** [comment]
I'm definitely not opposed to following the standard and adding a configurable option. The default would be the current behavior, but there could definitely be a "pure markdown" option or something like that in the settings.

**Comment by taw00** [comment]
Call it...  
[ ] "'soft line break' behavior (markdown)"   
... or some such. And I suppose it needs a help tooltip or something.

UX is hard. :)

**Comment by taw00** [comment]
Dead project. Closing.
