### ISSUE TITLE
UX tweak: double ESC while editing should not exit the editing process

### ISSUE THREAD

**Issue by taw00** [turtl/tracker#304]
If you are editing a note, and it still needs to be saved, and you hit ESC twice it will dump you out of the editor entirely thereby losing all your work. Ideally, if the note needs to be saved, it will circle back around as if you clicked "Cancel". Right now it does the equivalent of clicking "Ok" which is unexpected and dangerous. ESC is not quite the CTRL-C of the graphical UI world. :)

Thanks! I hope that was clear.

**Comment by orthecreedence** [comment]
What platform is this happening on? I'm using Windows and double-ESC keeps the note editor open.

**Comment by taw00** [comment]
Linux. Fedora 29 specifically. GNOME desktop.

**Comment by orthecreedence** [comment]
Thanks, I'll check this out on linux when I get a chance.

**Comment by Go-rom** [comment]
Hello
I can't reproduce that behavior under Linux Mint 19.1 64 bits

**Comment by taw00** [comment]
> Hello
> I can't reproduce that behavior under Linux Mint 19.1 64 bits

You began editing the document, then without saving, you hit ESC twice? If so and you didn't see this behavior... Hm... odd that I am.

**Comment by Go-rom** [comment]
Yes i did that.
Tried to create a new note, typed some random words then double hit ESC.
On the first hit, it displays a dialog box to warn me about my unsaved note.

Turtl version : 0.7.2.5 linux 64 bits

**Comment by taw00** [comment]
Yes. The dialogue shows up. "OK" Is highlighted. And ESC a second time will act as if you hit Return instead of ESC.

**Comment by Go-rom** [comment]
I tried that but didn't get this behaviour.
When i hit ESC a second time, the dialog box disappears but it doesn't close the ongoing note.

I'm running Linux Mint so i'll give a try with a live version of Fedora.

**Comment by taw00** [comment]
I wonder if it some subtle dialogue box default setting somewhere. Odd.

**Comment by taw00** [comment]
Dead project ... closing.
