### ISSUE TITLE
Add option to sort items in default view by title

### ISSUE THREAD

**Issue by elkoniu** [turtl/tracker#306]
It could be nice to be able to minimize all notes content and shrink them just to title. Then be able to display it in alphabetical / age order. Sometime searching through notes via search tool is overkill. Many peoples keeps similar notes with tittle starting with the same keyword like "Linux...", "Config of ..." etc.

**Comment by orthecreedence** [comment]
Hi, I think this is a duplicate of #220. Also, minimizing note content will be accomplished with #36!
