### ISSUE TITLE
Initial login fails on slow connection

### ISSUE THREAD

**Issue by ghost** [turtl/tracker#313]
Hi, I have problem that every day logging in to Turtl app v0.7.2.5 I have to retry loading profile upt to 15 times. I live in Indonesia, here internet is a bit slow and also govemental program of internet filtration adding pretty slow dns resolution as it only quiries forcesafeserach.google.com and not allow to use any other dns server. Can you please test turtl app for such slow connection with bigger timeout than usual? Also if your server located somehwere in EU or USA I think distance make things even harder.

Thank you.

**Comment by orthecreedence** [comment]
I will look into this.

**Comment by EternityForest** [comment]
Why does it have to connect to a server to load at all?  On Android I get errors loading even on WiFi in the US.   Seems like it should just load from offline storage and sync changes when it can.

**Comment by ghost** [comment]
Longe since moved on from using turtle, will close this issue, please re-open if anyone still need it.
