### ISSUE TITLE
0.7.2.6 osx a bit broken?

### ISSUE THREAD

**Issue by loogaru** [turtl/tracker#315]
Hello, I think that turtl-0.7.2.6-pre-sync-fix-osx is not working properly - I have completely removed previous version and tried to run latest, but it's not showing auth form, couldn't open debug info either.
Screencast: https://drive.google.com/open?id=1CkA5G3B0YCmJLwnZzz7FlTetYcK2tuqV
MacOS High Sierra 17G5019
Could it be related to translation?

PS: Tested in Android 7 (ok), Windows 10 (ok, but without translation)

**Comment by stuartellis** [comment]
I have the same issue on macOS Mojave 10.14.4 with a clean installation of turtl-0.7.2.6-pre-sync-fix-osx. No previous versions of Turtl have been installed on this system, so this is the first time starting the app. Unfortunately, there are no errors in the debug log.

**Comment by orthecreedence** [comment]
Thank you for the screen cast, that is helpful.

With the Turtl window focused, can you type `ctrl_shift+k` (or it might be `cm+shift+k` on OSx), open the "Console" tab, and either screenshot or paste anything you see in there? That would help a lot. 

Thanks!

**Comment by loogaru** [comment]
> main.js:696 Unhandled Promise error:  Error: [object Object]
>     at Object.Promise$_rejecter [as reject] (bluebird.js:2515)
>     at Omni.<anonymous> (_base.js:41)
>     at Omni.trigger (composer.js:574)
>     at Omni.trigger (composer.js:574)
>     at Omni.poll_messages (main.js:36)
>     at Omni.poll (main.js:29) Error: [object Object]
>     at Object.Promise$_rejecter [as reject] (file:///Applications/Turtl.app/Contents/Resources/app/build/app/lib/vnd/bluebird.js:2515:44)
>     at Omni.<anonymous> (file:///Applications/Turtl.app/Contents/Resources/app/build/app/lib/app/core-adaptors/_base.js:41:14)
>     at Omni.trigger (file:///Applications/Turtl.app/Contents/Resources/app/build/app/lib/vnd/composer.js:574:22)
>     at Omni.trigger (file:///Applications/Turtl.app/Contents/Resources/app/build/app/lib/vnd/composer.js:574:22)
>     at Omni.poll_messages (file:///Applications/Turtl.app/Contents/Resources/app/lib/app/core-adapter/main.js:36:8)
>     at Omni.poll (file:///Applications/Turtl.app/Contents/Resources/app/lib/app/core-adapter/main.js:29:8)

**Comment by orthecreedence** [comment]
Thanks! I'll take a look.

**Comment by orthecreedence** [comment]
Ok, figured this out. It was a problem in the build server itself. I'm going to close this without a release (v0.7.2.5 is still the official build for now).
