### ISSUE TITLE
Menu items are not working

### ISSUE THREAD

**Issue by loogaru** [turtl/tracker#318]
Hello
turtl-0.7.2.6-link-notes-osx, macOS High Sierra, self-hosted server, russian locale.
Screencast: https://drive.google.com/open?id=1EoLs6mVHvucHq18LBn1mloDDOGD64g9E
Same with Debug Info item on auth screen.
UPD: Same in android. Menu items in single-note-view works fine.

**Comment by orthecreedence** [comment]
Hi, @loogaru thanks for reporting. Does this happen with all menu items or only "Share this space?"

**Comment by loogaru** [comment]
_Notes screen_: every menu item is **broken**: "Share this space", "Settings"
_Single note screen_: every menu item works **fine**: "Copy link to note", "Delete", "Move note to another space"
_Auth screen_: the only item is **broken**: "Debug info"

**Comment by orthecreedence** [comment]
Thanks, this is very helpful.

**Comment by nick-denry** [comment]
Hi! I've created a PR to fix this issue.

https://github.com/turtl/js/pull/248
