### ISSUE TITLE
Turtl-server docker : Persistent Storage and WebUI ??

### ISSUE THREAD

**Issue by SirTerrific** [turtl/tracker#319]
HI,

I would like to host a turtl server with docker but I don't know which folders in the container I have to bind with my host. 
I already set for : 
- /uploads
- /plugins
For the DB
- /var/lib/postgresql/data
 
Also, I would like to know if I could change the "the default web view" of the service. I would like to have a simple webpages or something like that...

![Capture](https://user-images.githubusercontent.com/12296919/57670399-2164ff00-75dd-11e9-8bcd-77931c5b0e12.PNG)

Thanks for your work

**Comment by orthecreedence** [comment]
I think the folders you set up are correct.

As for the web ui, this is not currently possible, but there's a ticket tracking it: https://github.com/turtl/tracker/issues/246
