### ISSUE TITLE
Server setup fails during init-db.sh

### ISSUE THREAD

**Issue by chrismolli** [turtl/tracker#323]
Hey guys,

I am having a hard time setting up my own turtl server.
Nginx, Postgres and NodeJS are installed on the machine.

I configured my config.yaml as [config.txt](https://github.com/turtl/tracker/files/3317631/config.txt)
(I had to change the file type for GitHub).

The authentication with the db seems fine, if I enter a wrong user or password into the connstr, I get an auth error. Yet if I use a valid user and password the script always gets stuck at this point when running `init-db.sh`.

`Error: getaddrinfo EAI_AGAIN turtl:5432
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'turtl',
  host: 'turtl',
  port: 5432`

I looks like it tries to connect to `turtl:5432` instead of `127.0.0.1:5432`, but I don't know what could be wrong with my config at this point.

**Comment by chrismolli** [comment]
Well I found my error. I put a underscore `_` in my password, which broke the connectstr recognition ;)

**Comment by eandersons** [comment]
Thank you @chrismolli! In my case it was the symbol `#` in the password  that caused database initialization error.
I was suspecting that issue may be in the password, but I stubbornly tried to find problem and solution somewhere else until I found this issue.
