### ISSUE TITLE
"Error loading profile" on trying to log in

### ISSUE THREAD

**Issue by b-schliessmann** [turtl/tracker#328]
Hello everyone

On opening the respective client, it displays "Error loading profile" and offers the options "retry", "logout" and "clear local data".

Retry yields the same error, as does "logout" and trying to log in again. On both devices. It worked a few days ago.

My last export was a while ago, and the client doesn't allow me to export now -- can I safely try "clear local data" without losing my notes? Is there any possibility to back up manually before clearing the data?

Clients used:
- Android app 0.7.2.5
- Windows Client 0.7.2.5

Thanks and best regards

Björn

**Comment by orthecreedence** [comment]
Hi, this should be fixed now.

**Comment by b-schliessmann** [comment]
Hi, many thanks, it worked on first try in Windows. After trying the Android client with the above-mentioned error, Windows fails again too.

Please advise if I can help.

**Comment by b-schliessmann** [comment]
As of today, both clients are working again.

Many thanks.
