### ISSUE TITLE
Any incompatibility with Tutanota ?

### ISSUE THREAD

**Issue by Ra0EL** [turtl/tracker#345]
Hi guys,

I have a Tutanota email address, and I cannot receive anything :
 - when I try to register to **Turtl Community**.
 - when I try <https://turtlapp.com/users/delete/>

I am sure you will ask so : no, I don't have any problem with sending or receiving email from any domain with Tutanota account. But turtlapp.com, so.

Any idea ?

**Comment by orthecreedence** [comment]
Looking in the Sendgrid logs, I'm seeing:

```
This email was not sent because the email address previously bounced.

If you believe they should receive this type of email in the future, remove them from the Bounces suppression group. Learn more. 
```

This is for the email `g*******0@tutanota.com`. I'm not able to get the logs for more than 3 days since we're on the free account, but I can see in the bounce list:

```
2019/01/30 2:41am | 550 5.7.1 <g*******0@tutanota.com>: Recipient address rejected: Recipient not found
```
I have removed that email from the bounce list, so you should be able to try again. Let me know if it comes through.

**Comment by Ra0EL** [comment]
Hi Andrew,
thank you for quick reply.
Unfortunately I am still facing the same problem :
- I tried migration to v7 and it fails with an error message :
  ![Screenshot_20191118_140357](https://user-images.githubusercontent.com/8389138/69055671-a1e23d80-0a0e-11ea-8f76-982e2da37a98.png)  
  ![Screenshot_20191118_140527](https://user-images.githubusercontent.com/8389138/69055681-a6a6f180-0a0e-11ea-9b48-055e2f38d4a2.png)  
- I cannot receive confirmation email from Turtl Community

Just in case I have asked question to Tutanota support. They are not aware of any trouble with turtlapp.com domain. Could you confirm this is the correct domain for confirmation emails you send ?

Regards.

**Comment by orthecreedence** [comment]
Yes, turtlapp.com is the correct domain. Can you log in to that account (using your *new* email/password combo) and if you go into the app settings, there should be a link to send the confirmation again. Can you try that? You shouldn't need to migrate again.

**Comment by Ra0EL** [comment]
Hi,
a happy new year… and sorry for this belated answer !
Just to confirm this problem is fixed now.
Many thanks !
