### ISSUE TITLE
Turtl server S3

### ISSUE THREAD

**Issue by foguetes** [turtl/tracker#349]
Is it always necessary to have an S3 configured?

I would like to host everything myself.

**Comment by orthecreedence** [comment]
No, you'll see under `config.yaml.default` you can set `uploads.local` to a file path and uploads will be stored on the local disk of the server. You may also want to set `uploads.local_proxy` to true. Keep in mind storing files locally means you can only have one active instance of the Turtl server, but for most personal installations that is fine!
