### ISSUE TITLE
Is Turtl dead?

### ISSUE THREAD

**Issue by ghost** [turtl/tracker#357]
The Android app hasn't been updated in over a year and the last announcement on the website is clocking in at over two years ago.

**Comment by seelaman** [comment]
![image](https://user-images.githubusercontent.com/8989886/76499176-7d660300-63fb-11ea-8450-aa04291e8cfd.png)

Yes, does look pretty dead. It's a real shame it does pretty much exactly what I want except the Android client often just hangs with a white screen and needs to be restarted.

**Comment by rubbingalcoholic** [comment]
It's not dead. We are just busy with another project right now. Please be patient and feel free to contribute code if you are able.

**Comment by primarto** [comment]
Will there be upgrades in the future?
And is everything still safe to use?

**Comment by orthecreedence** [comment]
Yes, there will be updates, and all the cryptography is using [libsodium](https://doc.libsodium.org/) which is industry-standard for its cryptographic algorithms and ease of use (still safe).
