### ISSUE TITLE
Linking between notes

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#37]
Paste a special `note::1982b1fc9dfe19` into note text to link it to that note.

**Comment by orthecreedence** [comment]
Note that this would not just link to the other note, but would show a preview of the note. This would be helpful for embedding images or media uploaded to turtl into other notes.

**Comment by betsythefc** [comment]
This would be fantastic. I currently use Turtl in planning large overland trips where my group travels to the middle of nowhere. I have many notes involved in planning and linking between them in a "Master Note" would be amazing for organization. Is there a way to put a bounty on this feature?

**Comment by orthecreedence** [comment]
I haven't messed with bounties at all so not sure how to set it up, but I can certainly prioritize this feature. Certainly enough people have asked for it, or things that depend on it.

I'll mark it as v0.7.3, although there's a chance it might not make it in and would go in v0.7.4 instead.

**Comment by betsythefc** [comment]
I'm okay with a straight link that when clicked would open the note, or having it show a preview of the note/file/image. Either way works for me.

**Comment by JennyBourdiol** [comment]
+1 (waiting for "add image in a note")

**Comment by elgiorgio** [comment]
+1 for links between notes. That'd be very handy.

**Comment by tbdal** [comment]
is it correct that I multiple images from external sources can be inserted in one note but uploaded images can only remain in the then newly created note as the only image inside?

If that's the case +1 for linking of images (& other notes of course, too ;))

For bounties an easy way would be to use https://www.bountysource.com/

**Comment by orthecreedence** [comment]
> is it correct that I multiple images from external sources can be inserted in one note but uploaded images can only remain in the then newly created note as the only image inside?

Correct! Notes can only have one file (or image) attached. So if you want an image (or multiple images) from notes to show up in another, this would be the feature!

**Comment by orthecreedence** [comment]
https://github.com/turtl/desktop/releases/tag/v0.7.2.6-link-notes
https://github.com/turtl/android/releases/tag/v0.7.2.6-link-notes

Hey, everyone. Here's the first beta version of this feature. I'm going to close the issue for now, but please feel free to give feedback here still. Just wanted to give a preview of the feature before 0.7.3 releases.

**Comment by Ajackson126** [comment]
Are there any instructions available for how to use this feature. I can't seem to find any.
