### ISSUE TITLE
appimage please

### ISSUE THREAD

**Issue by omega3** [turtl/tracker#378]
Please, can you release appimage? 
I tried to install on Manjaro and there where some missing libraries. The same problem as [here](https://github.com/turtl/tracker/issues/356)

Neither Flatpak or snap packages are something I want to deal with at all. 

The biggest advantage of appimage is that it is portable and doesn't require installation. It can run on every distribution.

I don't know if it still valid but this might be an important issue about appimage to make it run without problem
https://github.com/netblue30/firejail/issues/2690#issuecomment-596204685

I am I right that is works offline, as a standalone application? 
If not you can disregard this request.

**Comment by ShamrockLee** [comment]
FYI: #63
