### ISSUE TITLE
Login failed -- Error: Cannot read property 'max_attemps' of undefined

### ISSUE THREAD

**Issue by colbach** [turtl/tracker#386]
Hello, when I try to log into Turtl from the desktop application I get the following error: Login failed -- Error: Cannot read property 'max_attemps' of undefined

I am using the current version of Fedora 32. I am sure to have used the right password. I already reinstalled Turtl.

EDIT: Same error on macOS

![Screenshot from 2021-01-20 00-51-33](https://user-images.githubusercontent.com/5789841/105108274-33898700-5aba-11eb-9803-57c3422a88d5.png)

**Comment by RockGet** [comment]
I am having the same issue on desktop and on android. This is preventing me from logging in. 

_Desktop debug log from when I try to log in_

> 2021-01-19T19:13:54 - [INFO][turtl_core::dispatch] dispatch(7): app:api:get-config
> 2021-01-19T19:14:03 - [INFO][turtl_core::dispatch] dispatch(8): app:api:set-config
> 2021-01-19T19:14:03 - [INFO][turtl_core::dispatch] dispatch(9): user:login
> 2021-01-19T19:14:03 - [INFO][turtl_core::models::user] user::generate_auth() -- generating v0 auth
> 2021-01-19T19:14:06 - [INFO][turtl_core::dispatch] dispatch(10): app:get-log

**Comment by drusalan** [comment]
Same as all above. MX19 and Android 9. Uninstalled, reinstalled, using correct password. What is going on here?

**Comment by colbach** [comment]
By the way. I just installed the application for testing purposes on macOS and the same problem occurs there.

**Comment by GitHub-user-2020** [comment]
Also tested on Windows 10 and Android 10, using the usual email and password I access Turtl with. Reading further into the debug log, I seem to be getting this:

`2021-01-20T00:45:28 - [DEBUG][turtl_core::api] api::call() -- call error: {"err":{"message":{"error":{"message":"Cannot read property 'max_attemps' of undefined"}},"subtype":"Internal Server Error","type":"api"},"file":"src\\api.rs","line":156,"wrapped":true}`

**Comment by moe20211** [comment]
omg I'm glad I'm not the only one experiencing this. Is this just a site issue? I can not afford to lose my files...

**Comment by drusalan** [comment]
"Cannot read property 'max_attemps' of undefined"

Should that read attempts? Is it looking for something like a variable 'max_attempts' that doesn't exist? Sorry not really a coder, just a poser.

**Comment by drusalan** [comment]
You know one thing did cross my mind. "Encrypted collaboration" might be frowned upon right now, with what is upcoming in the United States very shortly. Sharing recipes might be seen as a threat.

**Comment by orthecreedence** [comment]
Hi, this issue has been resolved. Was a code deployment issue ont the server itself.
