### ISSUE TITLE
GPG public signing key not found

### ISSUE THREAD

**Issue by jakerobers** [turtl/tracker#388]
[The download page](https://turtlapp.com/download/) has a GPG key for verifying the download. This link goes to keybase, but returns 404.

**Comment by orthecreedence** [comment]
Sorry, I had some issues with keybase recently. I'll try to get a new link up.

**Comment by orthecreedence** [comment]
Done!

The downloads page has been updated, and the new key location is here: https://keys.openpgp.org/vks/v1/by-fingerprint/DEDF113E54248344163716B55C66FAD13222D757

Thanks for bringing this to my attention!
