### ISSUE TITLE
Desktop / Mobile apps not working - Certificate expired - Let's Encrypt

### ISSUE THREAD

**Issue by mrk-te** [turtl/tracker#401]
Log in on my own server using Let's Encrypt certificate doesn't work anymore (Certificate expired)

The certificate is still valid but the Let's Encrypt DST Root CA X3 is expired since end of September 2021

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:35:30:3f:4b:4f:63:8a:a7:5e:7e:49:6a:14:7c:fd:1c:12
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = R3
        Validity
            Not Before: Oct 30 12:53:52 2021 GMT
            Not After : Jan 28 12:53:51 2022 GMT
```

I think an update of each mobile and desktop apps is required

**Comment by jecxjo** [comment]
I've only noticed this on my Android install. Both OSX and Windows desktop seem to be working for me.

**Comment by jecxjo** [comment]
Any movement on this ticket? Any self hosted servers using let's encrypt can no longer be accessed by mobile.

**Comment by bytersproblem** [comment]
turning on "skip ssl verification" solves the sync only with notes, but not with attachments.

**Comment by orthecreedence** [comment]
FYI the Turtl servers have been updated with one of those crappy $5 ssl certs, so this shouldn't be an issue at all with the service anymore. That said, using Let's Encrypt on self-hosted instances are broken for many people and I haven't found a good way to circumvent this. Might either need to self-sign and ignore the SSL errors, or shell out the $$ for "real" cert.

**Comment by jecxjo** [comment]
When updating `scripts/cacert.pem` what issue did you see? Thought the purpose of that file was to inject up to date root certs but looks like the main branch hasn't been updated since 2018. Trying to do a build right now with an updated file.

**Comment by sorcer1122** [comment]
I have got exactly the same problem - certificate expired, even though I generated it 10 mins ago. Any solution?

**Comment by sorcer1122** [comment]
Updating certificate with sudo certbot certonly --nginx -d <domain> --preferred-chain "ISRG Root X1" helps!
