### ISSUE TITLE
is turtl alive?

### ISSUE THREAD

**Issue by lucyferu** [turtl/tracker#419]
i was just wondering if this app still have developers, maintainers and/or community?
i found it on yunohost and i wanted to give it a go and i failed, but, before giving up, i went to check both the forum and github and both seems dead.
beside the fact the code hasn't been updated since 2019.

does anyone know more?

i guess, in this case, no answer will be an answer.

**Comment by orthecreedence** [comment]
Yeah, still around. Working on a new version, but life has been kicking my ass so it's slow going.

**Comment by lucyferu** [comment]
im sorry to hear about it. i hope you will get better soon. ❤️ 

excited to see what's new.
i saw turtl on yunohost and i wanted to give it a go, but the app isn't really working so i thought about checking.

i will definitely try the new version as soon as it comes out. 😸 

love and solidarity.
