### ISSUE TITLE
Space/board editors: rename "Edit <item>" button to "Save"

### ISSUE THREAD

**Issue by janos-szenfner** [turtl/tracker#80]
When I open a sapce to change it's color or set to default or share it there is no save button, just an Edit Space button which works as a save button.

Expected Result:
Save button with save text

Actual Result:
Edit Space button with save function

Version: 0.7
OS: Windows 10 64bit

**Comment by orthecreedence** [comment]
Thanks, Szefi. I'll update this before hte big release. Should be easy.
