### ISSUE TITLE
How to export data?

### ISSUE THREAD

**Issue by alejandroandreu** [turtl/tracker#81]
I've installed the Linux amd64 client to test Turtl out. What's the preferred way to back up my data?

Let's say for now I'm using the public API at https://api.turtl.it/v2 , but that later on I would like to roll out my own server and go from where I was.

**Comment by sthenault** [comment]
I use https://github.com/JulienPalard/turtl-backup for some time now and it works quite well.

**Comment by alejandroandreu** [comment]
Great, that'll do the trick! Thanks :smile:

**Comment by orthecreedence** [comment]
Also, v0.7.0 is going to be launching in a few weeks, and that will have built-in export/import of data.
