### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#96]
Obviously, a huge deal. Will probably rename `mobile` to `android` and copy/paste the project to `ios` just so we separate the codebases early on and not try to kid ourselves into thinking we can successfully keep everything in the same codebase when the bulk of the work is in an imported project (`js`) anyway.

**Comment by asdfghjz** [comment]
Duplicate of #24

**Comment by orthecreedence** [comment]
Oh, duh, thanks.
